### ISSUE TITLE
NullPointerException on WatchFileEvent in WeldPlugin

### ISSUE THREAD

**Issue by omasseau** [HotswapProjects/HotswapAgent#113]
JDK 1.7.0_79
hotswap-agent.jar v.0.3
wildlfy 9.0.2-Final

I am getting this error when creating a new class or renaming a class in my project:

14:36:23,690 INFO  [stdout] (Thread-1) HOTSWAP AGENT: 14:36:23.689 ERROR (org.hotswap.agent.watch.nio.WatcherNIO2) - Error in watch event 'WatchFileEvent on path C:\Users\maol\Developments\wildfly-9.0.2.Final\standalone\deployments\AofWeb.war\WEB-INF\classes\com\real\aof\tools\utils\Test3.class for event ENTRY_CREATE' listener 'org.hotswap.agent.plugin.weld.WeldPlugin$1@5364c838'
14:36:23,691 INFO  [stdout] (Thread-1) java.lang.NullPointerException

14:36:23,691 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.hashCode(BeanClassRefreshCommand.java:129)

14:36:23,692 INFO  [stdout] (Thread-1) 	at java.util.HashMap.hash(HashMap.java:362)

14:36:23,692 INFO  [stdout] (Thread-1) 	at java.util.HashMap.put(HashMap.java:492)

14:36:23,692 INFO  [stdout] (Thread-1) 	at java.util.Collections$SynchronizedMap.put(Collections.java:2041)

14:36:23,692 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.command.impl.SchedulerImpl.scheduleCommand(SchedulerImpl.java:52)

14:36:23,693 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.command.impl.SchedulerImpl.scheduleCommand(SchedulerImpl.java:34)

14:36:23,693 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.plugin.weld.WeldPlugin$1.onEvent(WeldPlugin.java:118)

14:36:23,694 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2.callListeners(WatcherNIO2.java:245)

14:36:23,694 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2.processEvents(WatcherNIO2.java:207)

14:36:23,694 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2.access$100(WatcherNIO2.java:32)

14:36:23,694 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2$2.run(WatcherNIO2.java:272)

14:36:23,695 INFO  [stdout] (Thread-1) 

14:36:23,698 INFO  [stdout] (Thread-1) HOTSWAP AGENT: 14:36:23.698 ERROR (org.hotswap.agent.watch.nio.WatcherNIO2) - Error in watch event 'WatchFileEvent on path C:\Users\maol\Developments\wildfly-9.0.2.Final\standalone\deployments\AofWeb.war\WEB-INF\classes\com\real\aof\tools\utils\Test3.class for event ENTRY_MODIFY' listener 'org.hotswap.agent.plugin.weld.WeldPlugin$1@5364c838'
14:36:23,698 INFO  [stdout] (Thread-1) java.lang.NullPointerException

14:36:23,699 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.hashCode(BeanClassRefreshCommand.java:129)

14:36:23,699 INFO  [stdout] (Thread-1) 	at java.util.HashMap.hash(HashMap.java:362)

14:36:23,699 INFO  [stdout] (Thread-1) 	at java.util.HashMap.put(HashMap.java:492)

14:36:23,699 INFO  [stdout] (Thread-1) 	at java.util.Collections$SynchronizedMap.put(Collections.java:2041)

14:36:23,700 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.command.impl.SchedulerImpl.scheduleCommand(SchedulerImpl.java:52)

14:36:23,700 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.command.impl.SchedulerImpl.scheduleCommand(SchedulerImpl.java:34)

14:36:23,700 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.plugin.weld.WeldPlugin$1.onEvent(WeldPlugin.java:118)

14:36:23,701 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2.callListeners(WatcherNIO2.java:245)

14:36:23,701 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2.processEvents(WatcherNIO2.java:207)

14:36:23,701 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2.access$100(WatcherNIO2.java:32)

14:36:23,701 INFO  [stdout] (Thread-1) 	at org.hotswap.agent.watch.nio.WatcherNIO2$2.run(WatcherNIO2.java:272)

14:36:23,701 INFO  [stdout] (Thread-1)

**Comment by skybber** [comment]
I've added more verbose error message to help resolve this problem. It would be great if you could test it with last repo version and help with it.

**Comment by skybber** [comment]
npe fixed
