### ISSUE TITLE
Tests failing with recent version from Git

### ISSUE THREAD

**Issue by awillinger** [HotswapProjects/HotswapAgent#117]
Just wanted to build the latest version from Git (last commit 2 days ago), but am failing at the tests for th Weld plugin.
Output:

    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Building hotswap-agent-weld-plugin 0.3.0-SNAPSHOT
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO]
    [INFO] [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO] Deleting D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target
    [INFO] [INFO]
    [INFO] [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] [INFO] skip non existing resourceDirectory D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\src\main\resources
    [INFO] [INFO]
    [INFO] [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO] Changes detected - recompiling the module!
    [INFO] [INFO] Compiling 9 source files to D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\classes
    [INFO] [INFO]
    [INFO] [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] [INFO] Copying 2 resources
    [INFO] [INFO]
    [INFO] [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO] Changes detected - recompiling the module!
    [INFO] [INFO] Compiling 12 source files to D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\test-classes
    [INFO] [WARNING] /D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/src/test/java/org/hotswap/agent/plugin/weld/WeldPluginTest.java: D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\src\test\java\org\hotswap\agent\plugin\weld\WeldPluginTest.java uses unchecked or unsafe operations.
    [INFO] [WARNING] /D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/src/test/java/org/hotswap/agent/plugin/weld/WeldPluginTest.java: Recompile with -Xlint:unchecked for details.
    [INFO] [INFO]
    [INFO] [INFO] --- maven-dependency-plugin:2.8:properties (default) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO]
    [INFO] [INFO] --- maven-surefire-plugin:2.15:test (default-test) @ hotswap-agent-weld-plugin ---
    [INFO] [INFO] Surefire report directory: D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\surefire-reports
    [INFO]
    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] HOTSWAP AGENT: 11:18:33.646 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.3.0-SNAPSHOT} - unlimited runtime class redefinition.
    [INFO] Running org.hotswap.agent.plugin.weld.WeldPluginTest
    [INFO] M▒r 14, 2016 11:18:34 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
    [INFO] INFO: WELD-000900: 2.2.6 (Final)
    [INFO] HOTSWAP AGENT: 11:18:34.303 DEBUG (org.hotswap.agent.plugin.weld.BeanDeploymentArchiveTransformer) - Class 'org.jboss.weld.environment.deployment.WeldBeanDeploymentArchive' patched with BDA registration.
    [INFO] HOTSWAP AGENT: 11:18:34.303 INFO (org.hotswap.agent.plugin.weld.WeldPlugin) - CDI/Weld plugin initialized.
    [INFO] HOTSWAP AGENT: 11:18:34.303 INFO (org.hotswap.agent.plugin.weld.WeldPlugin) - Registering archive path /D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/target/test-classes
    [INFO] HOTSWAP AGENT: 11:18:34.318 DEBUG (org.hotswap.agent.plugin.weld.command.BeanDeploymentArchiveAgent) - BeanDeploymentArchiveAgent registered bdaId='D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\test-classes' archivePath='/D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/target/test-classes'.
    [INFO] M▒r 14, 2016 11:18:34 AM org.jboss.weld.bootstrap.WeldStartup startContainer
    [INFO] INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
    [INFO] M▒r 14, 2016 11:18:34 AM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
    [INFO] WARN: WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
    [INFO] M▒r 14, 2016 11:18:34 AM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
    [INFO] WARN: WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
    [INFO] HOTSWAP AGENT: 11:18:34.881 DEBUG (org.hotswap.agent.plugin.weld.WeldPlugin) - Registering ProxyFactory : org.jboss.weld.bean.proxy.ProxyFactory
    [INFO] HOTSWAP AGENT: 11:18:34.881 DEBUG (org.hotswap.agent.plugin.weld.WeldPlugin) - Registering ProxyFactory : org.jboss.weld.bean.proxy.ProxyFactory
    [INFO] HOTSWAP AGENT: 11:18:35.021 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [org.hotswap.agent.plugin.weld.testBeans.HelloServiceImpl] (autoHotswap)
    [INFO] D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\test-classes
    [INFO] file:/D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/target/test-classes/NewClass.class
    [INFO] HOTSWAP AGENT: 11:18:36.725 TRACE (org.hotswap.agent.plugin.weld.WeldPlugin) - register reload command: NewClass
    [INFO] HOTSWAP AGENT: 11:18:36.725 ERROR (org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand) - Archive path '/D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/target/test-classes' doesn't match with classFullPath 'D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\test-classes\NewClass.class'
    [INFO] HOTSWAP AGENT: 11:18:36.725 TRACE (org.hotswap.agent.plugin.weld.WeldPlugin) - register reload command: NewClass
    [INFO] HOTSWAP AGENT: 11:18:36.725 ERROR (org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand) - Archive path '/D:/HotswapAgent/plugin/hotswap-agent-weld-plugin/target/test-classes' doesn't match with classFullPath 'D:\HotswapAgent\plugin\hotswap-agent-weld-plugin\target\test-classes\NewClass.class'
    [INFO] HOTSWAP AGENT: 11:18:37.287 TRACE (org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand) - isDeleteEvent result true: createFound=false, deleteFound={}
    [INFO] HOTSWAP AGENT: 11:18:37.756 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [org.hotswap.agent.plugin.weld.testBeans.HelloProducer] (autoHotswap)
    [INFO] HOTSWAP AGENT: 11:18:39.365 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [org.hotswap.agent.plugin.weld.testBeans.HelloServiceImpl] (autoHotswap)
    [INFO] Tests run: 8, Failures: 3, Errors: 4, Skipped: 0, Time elapsed: 7.016 sec <<< FAILURE! - in org.hotswap.agent.plugin.weld.WeldPluginTest
    [INFO] hotswapPrototypeTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 1.672 sec  <<< FAILURE!
    [INFO] java.lang.AssertionError: null
    [INFO]  at org.junit.Assert.fail(Assert.java:86)
    [INFO]  at org.junit.Assert.assertTrue(Assert.java:41)
    [INFO]  at org.junit.Assert.assertTrue(Assert.java:52)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.swapClasses(WeldPluginTest.java:198)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapPrototypeTest(WeldPluginTest.java:140)
    [INFO]
    [INFO] newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 1.031 sec  <<< ERROR!
    [INFO] java.lang.NullPointerException: null
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.getBean(WeldPluginTest.java:42)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean(WeldPluginTest.java:188)
    [INFO]
    [INFO] hotswapPrototypeTestNotFailWhenHoldingInstanceBecauseSingletonInjectionPointWasReinitialize(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 0 sec  <<< ERROR!
    [INFO] java.lang.NullPointerException: null
    [INFO]  at org.hotswap.agent.plugin.weld.testBeans.HelloServiceImpl.hello(HelloServiceImpl2.java:22)
    [INFO]  at org.hotswap.agent.plugin.weld.testBeans.DependentHello.hello(DependentHello.java:15)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapPrototypeTestNotFailWhenHoldingInstanceBecauseSingletonInjectionPointWasReinitialize(WeldPluginTest.java:163)
    [INFO]
    [INFO] hotswapRepositoryTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 1.61 sec  <<< FAILURE!
    [INFO] java.lang.AssertionError: null
    [INFO]  at org.junit.Assert.fail(Assert.java:86)
    [INFO]  at org.junit.Assert.assertTrue(Assert.java:41)
    [INFO]  at org.junit.Assert.assertTrue(Assert.java:52)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.swapClasses(WeldPluginTest.java:198)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapRepositoryTest(WeldPluginTest.java:103)
    [INFO]
    [INFO] hotswapSeviceAddMethodTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 1.625 sec  <<< FAILURE!
    [INFO] java.lang.AssertionError: null
    [INFO]  at org.junit.Assert.fail(Assert.java:86)
    [INFO]  at org.junit.Assert.assertTrue(Assert.java:41)
    [INFO]  at org.junit.Assert.assertTrue(Assert.java:52)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.swapClasses(WeldPluginTest.java:198)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapSeviceAddMethodTest(WeldPluginTest.java:83)
    [INFO]
    [INFO] hotswapServiceTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 0 sec  <<< ERROR!
    [INFO] java.lang.NullPointerException: null
    [INFO]  at org.hotswap.agent.plugin.weld.testBeans.HelloServiceImpl.hello(HelloServiceImpl2.java:22)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapServiceTest(WeldPluginTest.java:62)
    [INFO]
    [INFO] hotswapRepositoryNewMethodTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 0.016 sec  <<< ERROR!
    [INFO] java.lang.NullPointerException: null
    [INFO]  at org.hotswap.agent.plugin.weld.testBeans.HelloServiceImpl.hello(HelloServiceImpl2.java:22)
    [INFO]  at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapRepositoryNewMethodTest(WeldPluginTest.java:123)
    [INFO]
    [INFO]
    [INFO] Results :
    [INFO]
    [INFO] Failed tests:
    [INFO]   WeldPluginTest.hotswapPrototypeTest:140->swapClasses:198 null
    [INFO]   WeldPluginTest.hotswapRepositoryTest:103->swapClasses:198 null
    [INFO]   WeldPluginTest.hotswapSeviceAddMethodTest:83->swapClasses:198 null
    [INFO]
    [INFO] Tests in error:
    [INFO]   WeldPluginTest.newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean:188->getBean:42 NullPointer
    [INFO]   WeldPluginTest.hotswapPrototypeTestNotFailWhenHoldingInstanceBecauseSingletonInjectionPointWasReinitialize:163 ▒ NullPointer
    [INFO]   WeldPluginTest.hotswapServiceTest:62 ▒ NullPointer
    [INFO]   WeldPluginTest.hotswapRepositoryNewMethodTest:123 ▒ NullPointer
    [INFO]
    [INFO] Tests run: 8, Failures: 3, Errors: 4, Skipped: 0

If any more info is needed, please comment. Thanks in advance!

**Comment by skybber** [comment]
Strange, tests passed In my case. Skip them temprarily with mvn -Dmaven.test.skip=true package.
