### ISSUE TITLE
is it possible to be notified when autoload has done?

### ISSUE THREAD

**Issue by hooting** [HotswapProjects/HotswapAgent#118]
I worked with HotswapAgent well. 
However, I need to take actions after new classes has been reloaded. 
At present, HotswapAgent just print a message to Console, I wonder if it provides any API to check if new classes has been reloaded. In this way, I can take actions automatically

**Comment by allstone** [comment]
May I suggest you write your own plugin, then you can get notified inside it and take some actions there. I.e. fire event for classes in your package? Then just include plugin in hotswap.properties file and thats it.

**Comment by edudant** [comment]
This is the main purpose of HotswapAgent.

Have a look at http://www.hotswapagent.org/ha-plugins/how-to-write-a-plugin.
