### ISSUE TITLE
Anonymous classes not reloading with remote debuging

### ISSUE THREAD

**Issue by xGamingDudex** [HotswapProjects/HotswapAgent#121]
It might be something on my end, but have been trying on and off to fix this problem for around a over a week now and can't seem to find a solution to it. Any pointers in the correct direction would be much appreciated ;)

So as the title suggest, I'm currently unable to update classes while debuting remote applications. 
Everything works fine when I debug applications inside eclipse itself, and all updating/creating/removing/renaming etc of classes/methods/fields are working perfectly. Except for anonymous inner classes. I have tested using a small class with the current two classes:

Main:
```
public class Main {
	public static void main(String[] args) {
		while(true) {
			tick();
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}

	private static void tick() {
		System.out.println("Running runnable tick");
		new Runnable() {
			public void run() {
				System.out.println("Runnable");
				m2();
			}
		}.run();
		Class2.testM();
	}
	
	private static void m2() {
		System.out.println("Method2");
	}
}
```

Class2:
```
public class Class2 {
	
	public static void testM() {
		System.out.println("Test message");
	}

}

```

While debugging inside eclipse itself (Run as Debug -> Main) then everything works as normal. I can add methods inside the main class, can edit the strings and the output of the application changes accordingly.
If I however try to debug the application remotely (still on the same system) then I'm unable to edit anything inside the Main class. I can not change anything, not add/remove methods, not even the strings of the Runnable nor m2(). I can however successfully edit Class2.
Every time I save/build when debugging remote I get this line in the console of the remote application:
```
HOTSWAP AGENT: 13:49:9.132 RELOAD (org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin) - Class 'me/xadudex/playground/Main' has been enhanced with anonymous classes for hotswap.

```
So it clearly says that it reloaded the class, but it doesn't actually change anything.

I'm using this script to start the application:
```
#!/bin/bash
cd "`dirname "$0"`"

java -Xmx4G -Xms4G -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n -XXaltjvm=dcevm -javaagent:"/<path>/hotswap-agent-stable.jar" -jar test.jar

```
I know the path of the javaagent is correct as if I change it then the application won't start at all. I have also added these Java VM arguments to the eclipse JRE to get things working in local debugging (debugging inside eclipse) 
`-XXaltjvm=dcevm -javaagent:/<same path as above>/hotswap-agent-stable.jar`

I have patched java 8 using [DCEVM (light) for Java 8u74 (build 1)](https://github.com/dcevm/dcevm/releases/tag/light-jdk8u74%2B1) and have tried using both hot swap agent [0.3.0-SNAPSHOT@2016/02/15](https://github.com/HotswapProjects/HotswapAgent/releases/tag/0.3.0-SNAPSHOT%402016%2F02%2F15) and [RELEASE-0.3](https://github.com/HotswapProjects/HotswapAgent/releases/tag/RELEASE-0.3)

I'm using java 1.8.0 as the system java and JRE for eclipse

Output of "java -version":
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

Currently on Mac 10.9.5 using Eclipse 4.5.2.

I do apologize if this is the wrong place/format to report such problems. Also not sure if it is simply something wrong in my setup or if it is an actual bug somewhere. I'm fairly new to the HotSwapAgent project as a whole, but again, any help would be much appreciated.

**Comment by skybber** [comment]
You can check if redefinition is working by adding following argument -XX:TraceRedefineClasses=3, but probably it is not your case - you shouldn't see any trace redefinition message. Please ask this question on https://groups.google.com/forum/#!forum/hotswapagent - it is intended to common problems with DCEVM & HotswapAaagent.

**Comment by xGamingDudex** [comment]
Well as I mentioned redefinition is working. I can add/remove/rename/edit classes/fields/methods as long as they don't contain anonymous inner classes. I'll try and see if anyone may help over in the google group ;)
