### ISSUE TITLE
Spring 4.2.6: simple change in controller failing

### ISSUE THREAD

**Issue by nestoru** [HotswapProjects/HotswapAgent#138]
Hello guys,
I am trying to use DCEVM plus Hot Swap Agent in a project that uses Spring 4.2.6. A simple change in a string used as a parameter in a method invocation resulted in the below:

> HOTSWAP AGENT: 18:35:56.974 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'employeeController'
> HOTSWAP AGENT: 18:35:57.512 INFO (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Spring: clearing HandlerMapping for class org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping
> HOTSWAP AGENT: 18:35:57.514 ERROR (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Failed to clear HandlerMappings
> java.lang.NoSuchFieldException: handlerMethods
>   at java.lang.Class.getDeclaredField(Class.java:2070)
>   at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:44)
>   at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
>   at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
>   at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)

Thanks in advance,
- Nestor

**Comment by edudant** [comment]
This should work in current version. Please reopen if still valid.
