### ISSUE TITLE
Hotswap Agent not display logging message.

### ISSUE THREAD

**Issue by alive8e88** [HotswapProjects/HotswapAgent#142]
I using Hotswap Agent with Payara  4.1 for JSF project. I follow installation instruction from quick start. Everything work well, when I changed code Hotswap auto reload my changed. But I cannot see logging message when Hotswap agent working. My JDK version is 1.8.0_74.

**Comment by skybber** [comment]
Log messages are printed to System.out by default. You can define explicit logfile using LOGFILE property in hotswap-agent.properties file.

**Comment by alive8e88** [comment]
I checked my paraya log file but I cannot see any Hotswap agent's message.

**Comment by skybber** [comment]
Place it into classes folder. Look at README or https://github.com/HotswapProjects/HotswapAgentExamples
