### ISSUE TITLE
libresource.so: symbol JVM_GetManagementExt, version SUNWprivate_1.1 not defined in file libjvm.so with link time reference

### ISSUE THREAD

**Issue by lyssphacker** [HotswapProjects/HotswapAgent#147]
I'm using HotswapAgent with JDK 1.8.0_77 and WebLogic on Ubuntu 14.04.5 LTS. I cannot start WebLogic because of the following error:

**$HOME/Oracle/Middleware/Oracle_Home/oracle_common/jdk/bin/java: relocation error: $HOME/Oracle/Middleware/Oracle_Home/oracle_common/jdk/jre/lib/amd64/libresource.so: symbol JVM_GetManagementExt, version SUNWprivate_1.1 not defined in file libjvm.so with link time reference**

I am getting the same error on Fedora 25, but not on Windows 10. I tried to use different JDK versions, but without success. Is this known issue on some GNU/Linux distributions? Should I maybe install some package in order to solve the problem?

**Comment by skybber** [comment]
It is DCEVM related problem, not HotswapAgent. But you're probably mixing Oracle JVM libs with OpenJDK runtime.
