### ISSUE TITLE
Ignore IDE files

### ISSUE THREAD

**Issue by blabno** [HotswapProjects/HotswapAgent#16]
Let's remove *.iml, .ide, etc. files from VCS and add them to .gitignore.
Right now anytime I open my IntelliJ I get all those files as modified in changelist.

**Comment by pathikdevani** [comment]
how to ignore folder or file?
i am using HotswapAgent with plain java project. In my proect one folder "www" only with html,js,css file. i want to ignore this folder from HotswapAgent .

how?

**Comment by skybber** [comment]
Probably the question was put to wrong thread. The original problem was related to ignoring files in HotswapAgent project itself, not project using HotswapAgent. If you have problem with not ignoring files by HA in project using HA, please create a new issue and describe your problem better.
