### ISSUE TITLE
Publish to central

### ISSUE THREAD

**Issue by chadwilson** [HotswapProjects/HotswapAgent#163]
Is there any way we can get the agent jar published to central?  I have to manage these artifacts in a client's Nexus repository and it would be much more convenient to utilize the public repo

**Comment by edudant** [comment]
It is on our roadmap. It would be great, if you can help to create maven configuration for the project.

**Comment by cristatus** [comment]
I have configured it for maven central deployment. Please check http://central.sonatype.org/pages/ossrh-guide.html for further details.

**Comment by famod** [comment]
There is a mini-guide: https://maven.apache.org/guides/mini/guide-central-repository-upload.html
The maven configuration seems to be the smallest part, the bigger part is creating a PGP signature and [setting up Sonatype OSSRH](http://central.sonatype.org/pages/ossrh-guide.html) or something else.

So I suggest the HotswapAgent team should briefly read the guide and the linked resources to get an idea how others (like me) can contribute.

**Comment by JohnyIII** [comment]
http://repo1.maven.org/maven2/org/hotswapagent/

**Comment by edudant** [comment]
Thanks!

**Comment by Artur-** [comment]
Awesome!

But what is the 1.1.0 version which is deployed there? There is no such release in this repository

Also, was this a one time effort or are snapshots also deployed somewhere?

**Comment by JohnyIII** [comment]
well it is latest version of application, i got from master branch, i will release v 1.0 some time soon and when 1.1.0 is done, will release it too
