### ISSUE TITLE
info is unknown level?

### ISSUE THREAD

**Issue by lacivert** [HotswapProjects/HotswapAgent#170]
I am using Eclipse IDE, I made the necessary config to make my Java app run with hotswap agent + dcevm. It looks like working ok but there is always a log issue with this line:

`HOTSWAP AGENT: 09:03:58.732 WARNING (org.hotswap.agent.config.LogConfigurationHelper) - Invalid configuration value for property 'LOGGER'. Unknown LOG level 'info'`

Is there really an absence of the log level "info" or am I missing something about this?

**Comment by skybber** [comment]
I have no idea, what could be wrong. The appropriate HA code is

    AgentLogger.Level.valueOf(levelName.toUpperCase());

where levelName is 'info' in your case. Is there any HotswapAgent message preceeding your error message? What is your technology stack? Are you able to create a small project?

**Comment by lacivert** [comment]
I'll take a look deeper later but I can give you some information about two projects which I got this warning;
One was Spring 3.x, Hibernate (more than a year ago, I don't work on that project anymore) on Tomcat 6 and 7
Now the second; Jersey, JPA-Hibernate, again on Tomcat 7 with Maven & Eclipse debug configuration

**Comment by lacivert** [comment]
I am not sure but this may be the main problem: https://blog.codinghorror.com/whats-wrong-with-turkey/

If toUpperCase() function makes the word "info" to uppercase in Turkish language, it will be "İNFO" (with a dot on I which is different from I in English). Then the code should be changed as localization based uppercase/lowercase functions. I remember OrientDB had that issue and I reported the same problem to them and one line property changed and fixed the issue which I don't remember now. I'll check it again

**Comment by skybber** [comment]
WAW! It's new for me, but we can fix it easily. You can create PR, or I'll fix it in the evening. Thanks.

**Comment by lacivert** [comment]
I guess it should change like this: `AgentLogger.Level.valueOf(levelName.toUpperCase(Locale.ENGLISH));`
