### ISSUE TITLE
Values inside hotswap-agent.properties should accept dynamic variables using java System properties. (-D)

### ISSUE THREAD

**Issue by ghuser** [HotswapProjects/HotswapAgent#171]
It would be nice to be able to provide paths dynamically in the following way:

    extraClasspath=${base.project.directory}/module1/target/classes

And then provide this value when app or server starts, so that runtime filtering is applied:

    -Dbase.project.directory=/projects/myproject

This is very useful on multimodule projects (e.g. an ear with war/jar e.t.c), to eliminate the need for build-time filtering. (Build-time filtering might also require build-code to exclude the non-filtered version from monitored resources)

**Comment by skybber** [comment]
That makes sense !

**Comment by skybber** [comment]
Done in latest SNAPHOT release.
