### ISSUE TITLE
currentThread().getContextClassLoader().getResources(); returns two paths

### ISSUE THREAD

**Issue by ghuser** [HotswapProjects/HotswapAgent#172]
In the hotswap-agent.properties of a bare-bone (no-deps) project I've set:

    extraClasspath=/projects/HotSwapTests/resoverride

When using code like this to access a resource:

```java
Enumeration<URL> en = Thread.currentThread().getContextClassLoader().getResources("test.xml");
for(;en.hasMoreElements();){
    System.out.println(en.nextElement());
}
```

I get the following output:

    file:/projects/HotSwapTests/resoverride/test.xml
    jar:file:/projects/HotSwapTests/target/HotSwapTests-1.0-SNAPSHOT.jar!/test.xml

Is this normal?

Shouldn't the output only contain the first line?
Due to this, resource overriding does not work in a framework that I use, and Its not clear to me  whether this should be considered a framework or a hotswap bug.

**Comment by skybber** [comment]
There is [class loaders hiearchy](https://docs.oracle.com/cd/E19501-01/819-3659/beadf/index.html) in JVM. For instance [URLClassLoader getResouces()](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/ClassLoader.java#ClassLoader.getResources%28java.lang.String%29) calls parent getResources() and joins results. There is a classloader for .jar file returning 

    jar:file:/projects/HotSwapTests/target/HotSwapTests-1.0-SNAPSHOT.jar!/test.xml

,you have probably test.xml inside jar. Anyway there is `watchResources=` [configuration property](http://hotswapagent.org/mydoc_configuration.html) intended to resources overriding.

**Comment by ghuser** [comment]
Watch resources though is not persistent across service restarts, because it only applies overrides when files are modified.

`extraClasspath` from the other side is overriding resources correctly across restarts but has the problem described above.
 
e.g. However If (having set only `extraClasspath`) someone uses :

    Main.class.getResourceAsStream("/test.xml")

it gets the overwritten content correctly.
