### ISSUE TITLE
Thread.currentThread().getContextClassLoader().getResources() does not load resources from 'watchResources' dir

### ISSUE THREAD

**Issue by ghuser** [HotswapProjects/HotswapAgent#176]
[HotSwapTests.zip](https://github.com/HotswapProjects/HotswapAgent/files/794412/HotSwapTests.zip)

I use jdk1.8.0_121. I run the simple example above (for testing purposes it never terminates) then I update `test.xml` inside the directory defined in `watchResources` and `currentThread().getContextClassLoader().getResources();` still returns the same results. 
Only the return value of `Main.class.getResourceAsStream()` changes.

**Comment by skybber** [comment]
There was some missing code for multi-resource methods. Thanks for report!

**Comment by ghuser** [comment]
It works!
But I think this creates a new Issue. When `extraClasspath` is enabled (nomatter what the path is), `currentThread().getContextClassLoader().getResources()` is empty.
