### ISSUE TITLE
autoHotswap: Missing watch event error when saving files in plain java project

### ISSUE THREAD

**Issue by messedcircuit** [HotswapProjects/HotswapAgent#182]
Using the latest Java8 DCEVM on jdk update 112 from eclipse with autoHotswap enabled, running the program does print out: 
`
HOTSWAP AGENT: 22:02:03.064 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.1.0-SNAPSHOT} - unlimited runtime class redefinition.
`

`
HOTSWAP AGENT: 22:02:03.525 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory target A:\pathtofile
`

`
HOTSWAP AGENT: 22:02:03.527 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'sun.misc.Launcher$AppClassLoader@18b4aac2'.
`

`
HOTSWAP AGENT: 22:02:03.600 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, WatchResources, AnonymousClassPatch, ClassInitPlugin, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, JavaBeans, GlassFish]
`

But saving any java file in the project during execution gives the following error: 

`HOTSWAP AGENT: 22:02:15.343 ERROR (org.hotswap.agent.watch.nio.EventDispatcher) - No match for  watch event 'sun.nio.fs.AbstractWatchKey$Event@2c007937',  path 'A:\pathtofile\Class.java'
`

**Comment by sachinkakkar7** [comment]
Hi, 
Are you using tomcat or JBoss?? Can you please share how you have set the DCEVM. I recently did the set up using java 8 + DCEVM+ hot swap agent with JBoss and all the features (except 2-(creation of regular or inner class, declaring and initializing class fields) are working fine. I can try to help u out.

**Comment by messedcircuit** [comment]
Neither tomcat nor JBoss, it's a plain java project. DCEVM was installed on top of a freshly installed java 8 using the installer with the altjvm option (home directory, in A:\java\jdk\1.8_112\), and I set up eclipse to use it (also A:\java\jdk\1.8_112\) as the only jre, restarted and run the project with vm args: 
`-XXaltjvm=dcevm -javaagent:a:\java\hotswap\hotswap-agent.jar` 

Later tried the exact same project under the JRebel trial (using a separate jdk), and got that working.

**Comment by skybber** [comment]
Save compiled Class.class file, not Class.java to extraClasspath.

**Comment by messedcircuit** [comment]
Thank you, pointing extraClasspath or putting the hotswap-agent.properties file inside the bin directory recompiles classes properly!
