### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: org/springframework/core/io/Resource with hotswap-agent-1.1.0-SNAPSHOT(latest version)

### ISSUE THREAD

**Issue by sachinkakkar7** [HotswapProjects/HotswapAgent#184]
Hi,

I have properly configured DCEVM and Hotswap agent. Whenever I make a change, save and re-compile a file(name-DestinationResource. It has annotations) using IntelliJ, the below logs are seen in JBoss' console

RedefineClasses-0x1: Redefinition with revision number 0 started!
RedefineClasses-0x1: loading new class versions (1)
RedefineClasses-0x1: Class being reloaded: com/att/adtm/auth/destination/resource/DestinationResource
RedefineClasses-0x1: 1 classes affected
RedefineClasses-0x1: Redefine order:
RedefineClasses-0x1: com/att/adtm/auth/destination/resource/DestinationResource
RedefineClasses-0x1: Processing affected class com/att/adtm/auth/destination/resource/DestinationResource (1 of 1)
RedefineClasses-0x1: Comparing different class versions of class com/att/adtm/auth/destination/resource/DestinationResource
RedefineClasses-0x1: Super class is com/att/adtm/common/resource/AdtmBaseResource
RedefineClasses-0x1: Linking class 0/1 com/att/adtm/auth/destination/resource/DestinationResource
RedefineClasses-0x1: All classes loaded!
RedefineClasses-0x1: Finished verification!
RedefineClasses-0x1: Loaded new class versions!
RedefineClasses-0x1: doit_prologue finished!
RedefineClasses-0x1: Before updating instances
RedefineClasses-0x1: After updating instances
RedefineClasses-0x1: Copying static field value for field LOGGERUTIL old_offset=104 new_offset=104
RedefineClasses-0x1: Copying static field value for field MAX_ADDRESS_COUNT old_offset=108 new_offset=108
RedefineClasses-0x1: GC Operation epilogue 

But as soon as I press F6(during debugging)I get the below exception.

16:46:43,752 ERROR [stderr] (Thread-276) Exception in thread "Thread-276" **java.lang.NoClassDefFoundError: org/springframework/core/io/Resource**
16:46:43,793 ERROR [stderr] (Thread-276)        at java.lang.Class.getDeclaredMethods0(Native Method)
16:46:43,947 ERROR [stderr] (Thread-276)        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
16:46:49,070 ERROR [stderr] (Thread-276)        at java.lang.Class.getDeclaredMethod(Class.java:2128)
16:46:49,137 ERROR [stderr] (Thread-276)        at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:72)
16:46:49,708 ERROR [stderr] (Thread-276)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
16:46:49,712 ERROR [stderr] (Thread-276) Caused by: java.lang.ClassNotFoundException: org.springframework.core.io.Resource

Here is what I am using
1. DCEVM-light-8u112-installer.jar + hotswap-agent-1.1.0-SNAPSHOT(latest version) + Java 1.8.0_111
2. Deployed an un-exploded EAR in JBOSS 7.
3. Code is using spring and hibernate frameworks

Please suggest a possible solution to this problem.

**Comment by skybber** [comment]
May be same problem as in  #183

**Comment by sachinkakkar7** [comment]
That's right.

**Comment by skybber** [comment]
fixed in snapshot 1.1.0-SNAPHOT
