### ISSUE TITLE
JVM crashes while trying to save a modified file

### ISSUE THREAD

**Issue by sachinkakkar7** [HotswapProjects/HotswapAgent#188]
JVM crashes when I try to save a modified file. Here is what I am using

1. DCEVM-light-8u112-installer
2. hotswap-agent-1.1.0-SNAPSHOT
3. Spring 4.3.7
4. JBOSS 7

Here are the logs
10:48:43,213 INFO  [stdout] (default task-1) Details Needed - ClassLoader ModuleClassLoader for Module "deployment.SpringTest.war:main" from Service Module Loader
RedefineClasses-0x1: Redefinition with revision number 0 started!
RedefineClasses-0x1: loading new class versions (2)
RedefineClasses-0x1: Class being reloaded: com/tutorialspoint/HelloController
RedefineClasses-0x1: Class being reloaded: com/tutorialspoint/HelloController
RedefineClasses-0x1: 2 classes affected
RedefineClasses-0x1: Redefine order:
RedefineClasses-0x1: com/tutorialspoint/HelloController
RedefineClasses-0x1: com/tutorialspoint/HelloController
RedefineClasses-0x1: Processing affected class com/tutorialspoint/HelloController (1 of 2)
10:48:48,486 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 10:48:48.486 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory target C:\Program Files\JBoss\modules\system\layers\base\org\jboss\as\ejb3\main\timers via watched: C:\Program
10:48:48,486 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 10:48:48.486 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory target C:\Program Files\JBoss\modules\system\layers\base\sun\jdk\main\service-loader-resources via watched: C:
10:48:48,486 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 10:48:48.486 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory target C:\Program Files\JBoss\modules\system\layers\base\sun\scripting\main\service-loader-resources via watch
10:48:48,486 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 10:48:48.486 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory target C:\Workspaces\DCEVM_Workspace\SpringTest\WebContent\WEB-INF\classes via watched: C:\Workspaces\DCEVM_Wo
10:48:48,502 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 10:48:48.502 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'ModuleClassLoader for Module "deployment.Spri
RedefineClasses-0x1: Comparing different class versions of class com/tutorialspoint/HelloController
RedefineClasses-0x1: Super class is java/lang/Object
RedefineClasses-0x1: Processing affected class com/tutorialspoint/HelloController (2 of 2)
RedefineClasses-0x1: Comparing different class versions of class com/tutorialspoint/HelloController
RedefineClasses-0x1: Super class is java/lang/Object
RedefineClasses-0x1: Linking class 0/2 com/tutorialspoint/HelloController
RedefineClasses-0x1: Linking class 1/2 com/tutorialspoint/HelloController
RedefineClasses-0x1: All classes loaded!
RedefineClasses-0x1: Finished verification!
RedefineClasses-0x1: Loaded new class versions!
RedefineClasses-0x1: doit_prologue finished!
RedefineClasses-0x1: Before updating instances
RedefineClasses-0x1: After updating instances
RedefineClasses-0x1: GC Operation epilogue finished!
RedefineClasses-0x1: Redefinition finished!
10:48:48,845 INFO  [stdout] (Thread-293) HOTSWAP AGENT: 10:48:48.829 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.tutorialspoint.HelloController] (autoHotswap)
10:48:48,845 INFO  [stdout] (Thread-292) HOTSWAP AGENT: 10:48:48.829 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.tutorialspoint.HelloController] (autoHotswap)
RedefineClasses-0x1: Redefinition with revision number 1 started!
RedefineClasses-0x1: loading new class versions (1)
RedefineClasses-0x1: Class being reloaded: com/tutorialspoint/HelloController
RedefineClasses-0x1: 1 classes affected
RedefineClasses-0x1: Redefine order:
RedefineClasses-0x1: com/tutorialspoint/HelloController
RedefineClasses-0x1: Processing affected class com/tutorialspoint/HelloController (1 of 1)
RedefineClasses-0x1: 10:48:48,876 INFO  [stdout] (Thread-294) HOTSWAP AGENT: 10:48:48.845 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'helloController'
Redefinition with revision number 2 started!
RedefineClasses-0x1: loading new class versions (1)
RedefineClasses-0x1: Class being reloaded: com/tutorialspoint/HelloController
RedefineClasses-0x1: 1 classes affected
RedefineClasses-0x1: Redefine order:
RedefineClasses-0x1: com/tutorialspoint/HelloController
RedefineClasses-0x1: Processing affected class com/tutorialspoint/HelloController (1 of 1)
10:48:48,923 INFO  [stdout] (Thread-291) HOTSWAP AGENT: 10:48:48.907 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'helloController'
RedefineClasses-0x1: Comparing different class versions of class com/tutorialspoint/HelloController
RedefineClasses-0x1: Super class is java/lang/Object
RedefineClasses-0x1: Linking class 0/1 com/tutorialspoint/HelloController
RedefineClasses-0x1: All classes loaded!
RedefineClasses-0x1: Finished verification!
RedefineClasses-0x1: Loaded new class versions!
RedefineClasses-0x1: doit_prologue finished!
RedefineClasses-0x1: Before updating instances
RedefineClasses-0x1: After updating instances
RedefineClasses-0x1: GC Operation epilogue finished!
RedefineClasses-0x1: Redefinition finished!
**10:48:49,219 INFO  [stdout] (Thread-292) HOTSWAP AGENT: 10:48:49.219 ERROR (org.hotswap.agent.util.HotswapTransformer) - Error transforming class 'com/tutorialspoint/HelloController'.**
**10:48:49,235 INFO  [stdout] (Thread-292) java.lang.NullPointerException
10:48:49,235 INFO  [stdout] (Thread-292)        at java.util.Hashtable.put(Hashtable.java:459)
10:48:49,235 INFO  [stdout] (Thread-292)        at org.hotswap.agent.javassist.ClassPool.cacheCtClass(ClassPool.java:258)**
10:48:49,235 INFO  [stdout] (Thread-292)        at org.hotswap.agent.javassist.CtClass.detach(CtClass.java:1350)
10:48:49,251 INFO  [stdout] (Thread-292)        at org.hotswap.agent.plugin.spring.SpringChangesAnalyzer.classChangeNeedsReload(SpringChangesAnalyzer.java:49)
10:48:49,251 INFO  [stdout] (Thread-292)        at org.hotswap.agent.plugin.spring.SpringChangesAnalyzer.isReloadNeeded(SpringChangesAnalyzer.java:36)
10:48:49,266 INFO  [stdout] (Thread-292)        at org.hotswap.agent.plugin.spring.SpringPlugin$1.transform(SpringPlugin.java:80)
10:48:49,266 INFO  [stdout] (Thread-292)        at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:189)
10:48:49,266 INFO  [stdout] (Thread-292)        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
10:48:49,282 INFO  [stdout] (Thread-292)        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
10:48:49,282 INFO  [stdout] (Thread-292)        at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
10:48:49,282 INFO  [stdout] (Thread-292)        at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
10:48:49,297 INFO  [stdout] (Thread-292)        at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:269)
10:48:49,297 INFO  [stdout] (Thread-292)        at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin$1.executeCommand(HotswapperPlugin.java:94)
10:48:49,297 INFO  [stdout] (Thread-292)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
10:48:49,313 INFO  [stdout] (Thread-292)
RedefineClasses-0x1: 10:48:49,313 INFO  [stdout] (Thread-295) HOTSWAP AGENT: 10:48:49.313 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'helloController'
Comparing different class versions of class com/tutorialspoint/HelloController
RedefineClasses-0x1: Super class is java/lang/Object
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000007f3dd5c, pid=12128, tid=0x0000000000002948
#
# JRE version: Java(TM) SE Runtime Environment (8.0_112-b15) (build 1.8.0_112-b15)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.71-b01-dcevmlight-8 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x1add5c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\sk032e\Desktop\hs_err_pid12128.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/dcevm/dcevm/issues
#
Press any key to continue . . .

**Comment by skybber** [comment]
Author used =autoHotswap=True together with debugging, this combination [should be avoided](http://hotswapagent.org/mydoc_configuration.html#auto-hotswap). In this case duplicate redefinitions are sent to JVM.

**Comment by sachinkakkar7** [comment]
Thanks for helping in resolving this issue.

**Comment by skybber** [comment]
Not at all, belive it is helfull now ! Looks there is some issue in remote
debugging...

regards Vladimir

2017-03-20 21:23 GMT+01:00 sachinkakkar7 <notifications@github.com>:
