### ISSUE TITLE
Question - Where to put hotswap-agent.properties file for an exploded EAR

### ISSUE THREAD

**Issue by sachinkakkar7** [HotswapProjects/HotswapAgent#189]
Hi,

I have successfully tested DCEVM[latest] + Hotswap agent[latest] with a sample Hello world Spring application. Now I am trying to integrate DCEVM and Hotswap agent with another spring application from our project which is getting deployed as an unexploded EAR in JBOSS 7.

Here's the structure which shows where the JAR having .class files is present.

**TEST-PORTAL\APP-INF\lib\CORE_classes.jar**

Earlier I kept the hotswap-agent.properties in target\classes folder but that's not getting read. Whenever I change a java file and save it(to recompile), nothing appears in the console and change isn't picked up. I am assuming that the directory where .class files are , isn't getting watched.

here is the content of hotswap-agent.properties
**extraClassPath=c:\workspaces\TESTPortal\CORE\target\classes**

please help

**Comment by skybber** [comment]
Multi ear can be problem, try to pack hotswap-agent.properties (with extraClassPath) within CORE_classes.jar

**Comment by sachinkakkar7** [comment]
Tried the below option with no luck

1. Added hotswap-agent.properties to module's src->main->resources


hotswap-agent.properties is still not being read. Its getting packed within
CORE_classes.jar

**Comment by sachinkakkar7** [comment]
I was able to make it work for my multi-module application. It was just about placing hotswap-agent.properties in the class path root of project. Hot swapping features are working as expected. Thanks for the support.
This thread can be closed now.

**Comment by krizajb** [comment]
Mind giving a little help with my setup, HA is working but not when adding a method to the class. Currently I am running HA without agent.properties file. 
Ear is composed of ejb.war, web.war and another .war file. Not sure where exactly I should put the agent.properties and what should be extraClassPath pointing to. Thanks.
