### ISSUE TITLE
HotswapAgent is stop JVM in Spring MVC 4X project (add new method)

### ISSUE THREAD

**Issue by wagamama06** [HotswapProjects/HotswapAgent#208]
When my project work and I add new method in Controller class, HotswapAgent is stopped my project and written below error.

	@RequestMapping(value = "/urlAdresses.ajax")
	@ResponseBody
	public Map<String, Object> metod1(@RequestParam String id,,HttpServletResponse resp) {
		return bus.metod1(id);
	}

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000054c7dd4c, pid=9148, tid=0x0000000000002c50
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.71-b01-dcevmlight-9 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x1add4c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# ..\workspace-project\project-backend\hs_err_pid9148.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/dcevm/dcevm/issues
#

**Comment by skybber** [comment]
Ok, please don't use bold text. Next, it is probably DCEVM issue since JVM crashes. Add new DCEVM issue and supply more information from hs_err_pid9148.log. Thanks.

**Comment by wagamama06** [comment]
ok thanks
