### ISSUE TITLE
NoSuchMethodError: org.jboss.weld.bootstrap.spi.BeansXml.getUrl()

### ISSUE THREAD

**Issue by iovuio** [HotswapProjects/HotswapAgent#210]
Environment:

HotSwapAgent version: [1.1.0-SNAPSHOT](https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.1.0-SNAPSHOT)

Glassfish version: file [ogs-3.1.2.2.zip](http://www.oracle.com/technetwork/middleware/glassfish/downloads/ogs-3-1-1-downloads-439803.html) with some custom configuration as described in the steps below.

Java version 7u79 altjvm patched with corresponding version of DCEVM installed in a directory referred to as JAVA_DCEVM below. Used for starting Glassfish.

**Steps:**
1. Download HotSwapAgent (hotswap-agent-1.1.0-SNAPSHOT.jar) to /hotswap-agent-1.1.0-SNAPSHOT.jar (referred to as HA_INST below)
2. Download Glassfish application server full 3.1.2.2 (ogs-3.1.2.2.zip) unzip to /glassfish3 (referred to as GF_INST below)
3. Copy hotswap-agent-1.1.0-SNAPSHOT.jar from `HA_INST` to `<GF_INST>/glassfish/domains/domain1/lib/ext`
4. Edit `<GF_INST>/glassfish/domains/domain1/config/domain.xml`
+ *Remove*
    `  <jvm-options>-client</jvm-options>`

+ *Add*
`<jvm-options>-XXaltjvm=dcevm</jvm-options>`
`<jvm-options>-javaagent:<HA_INST>/hotswap-agent-1.1.0-SNAPSHOT.jar</jvm-options>`

5. Glassfish 3 requires the admin user to be enabled. The following procedure will provide that.
`<GF_INST>/bin/asadmin start-domain domain1`
provide master password.
Enable secure admin
`<GF_INST>/bin/asadmin enable-secure-admin`
Stop the domain
`<GF_INST>/bin/asadmin stop-domain domain1`

6. In the IDE, open the attached [sample-project](https://github.com/HotswapProjects/HotswapAgent/files/1236517/sample-project.zip), start a debug session on Glassfish 3 at `<GA_INST>` with altjvm patched Java 7u79 at `<JAVA_DCEVM>`.

**Expected result**
Application successfully deployed with HotSwapAgent.

**Actual Result**
Error during deployment occurs. Logged in the `<GF_INST>/glassfish/domains/domain1/logs/server.log`

`Caused by: java.lang.NoSuchMethodError: org.jboss.weld.bootstrap.spi.BeansXml.getUrl()Ljava/net/URL;
	at org.hotswap.agent.plugin.weld.command.BeanDeploymentArchiveAgent.registerArchive(BeanDeploymentArchiveAgent.java:58)
	... 40 more
`

**Comment by skybber** [comment]
Thank you for perfect description. It looks you're using Weld v1.x. HotswapAgent has support for Weld versions>=2.0. Best you can do now is to disable the Weld plugin to get rid of that errors.

**Comment by iovuio** [comment]
@skybber thank you for your prompt reply.

Indeed, Glassfish 3.1.2.2 seems to be using Weld 1.1.4 ([reference page](http://www.oracle.com/technetwork/middleware/glassfish/downloads/glassfish-312-3rdparty-readme-1521433.html))
Upon disabling weld plugin as on the line below:
`<jvm-options>-javaagent:<HA_INST>/hotswap-agent-1.1.0-SNAPSHOT.jar=disablePlugin=weld</jvm-options>`
the error in the description is not occurring anymore.
