### ISSUE TITLE
Equinox/OSGI: NPE in PluginClassFileTransformer.java:88

### ISSUE THREAD

**Issue by Chaniro** [HotswapProjects/HotswapAgent#213]
Hello,

I try to use HotswapAgent with the Equinox/OSGI plugin. However, when I perform a hotswap, I got the following error:

> HOTSWAP AGENT: 11:16:16.141 ERROR (org.hotswap.agent.util.HotswapTransformer) - Error transforming class 'com.example.Test$1'.
java.lang.NullPointerException
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:88)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:187)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)

Environment:
- IntelliJ
- DCEVM (light) for Java 8u144 (build 2)
- Agen: 1.1.0-SNAPSHOT

JVM arguments: 

> -Dosgi.frameworkParentClassloader=app
-Dosgi.dev=C:/out
-XXaltjvm=dcevm
-javaagent:C:\lib\hotswap-agent.jar
-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:4452,suspend=y,server=n (added by Intellij)

hotswap-agent.properties:

> extraClasspath=C:/out
osgiEquinox.debugMode=true

I have no clue why I'm getting this error. Any idea ?
Thanks ! :)

**Comment by skybber** [comment]
Did you define or redefine anonymous (inner) class com.example.Test$1 ? It can be caused by race condition when the new class is not present on extraClasspath=C:/out

**Comment by Chaniro** [comment]
No, I just add a simple println for testing purpose (body modification of an existing inner class). I go the same NPE for all inner class and for the class itself (Test, Test$1, Test$2...).
I just notice that event if I set output directory for all my module in IntelliJ to "C:/out", Intellij creates one folder per module inside.
My out directory looks like this:
> C:/out/module1/com/example/SomeClass.class
C:/out/module2/com/example2/OtherClass.class

Is it a problem ? Maybe the hierarchy should start directly at "com/...." inside the "out" directory ?

For more, I pulled the repo. I noticed that in [PluginClassFileTransformer:88](https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/annotation/handler/PluginClassFileTransformer.java#L88), you get the PluginConfiguration from the ClassLoader. The given ClassLoader is an instance of **org.eclipse.osgi.internal.loader.EquinoxClassLoader** and I have 2 ClassLoader as a key of the _classLoaderConfigurations_ map in the PluginManager :
- **org.eclipse.equinox.launcher.Main$StartupClassLoader**
- **sun.misc.Launcher$AppClassLoader**.

I don't know if this information can help you.

**Comment by skybber** [comment]
It looks that the osgiequinox plugin is not initialized. HA put osgiequinox plugin's initialization hook  into constructor of `org.eclipse.osgi.launch.Equinox` - you can se [it here](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-osgiequinox-plugin/src/main/java/org/hotswap/agent/plugin/osgiequinox/OsgiEquinoxPlugin.java#L76). Clearly it doesn't work in your case - it means that the `class org.eclipse.osgi.launch.Equinox` is not loaded or no instance is created. What osgiequinox version are you using? (I've tested it with osgiequinox in eclipse 4.4.)

**Comment by Chaniro** [comment]
The pach is working since `Pluginregistry.initializePlugin` is called right after `org.eclipse.osgi.launch.Equinox` constructor. However, it puts an `org.eclipse.equinox.launcher.Main$StartupClassLoader` in the _classLoaderConfigurations_, not an `org.eclipse.osgi.internal.loader.EquinoxClassLoader` which I need 

I tried to force _getPluginConfiguration_ to return this `StartupClassLoader` but my IDE got stuck when I hotswap (I guess it's not the right ClassLoader so it doesn't "see" changes).

I'm using `org.eclipse.osgi-3.11.3`.

**Comment by skybber** [comment]
Please, could you contact me by email?

**Comment by Chaniro** [comment]
Sure

**Comment by skybber** [comment]
Hi Bastien,

I've found bug that can be related to your original problem
NPE in PluginClassFileTransformer.java:88

I've updated updated SNAPHOT release files

https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.1.0-SNAPSHOT


it could be better to use this one instead hacked version as I've suggested.


regards vladimir

2017-10-04 14:53 GMT+02:00 Bastien BARET <notifications@github.com>:

**Comment by Chaniro** [comment]
Hi Vladimir,

The NPE seems to be fixed however I can't hotswap: my IDE (Intellij) seems to wait for the hotswap to be done. Maybe it doesn't detect changes or the hotswap isn't correctly performed ?

**Comment by skybber** [comment]
You can check if redefinition is actually done by JVM using JVM param
-XX:TraceRedefineClasses=1, JVM writes redefinition info into stdout.

Unfortunatelly I have no experience with IntelliJIdea, may be you have some
problem in your setup. You can check how extraClassPath works

in OsgiEquinoxPlugin.classReload().  This method is called before
redefinition in JVM.

The chain of calls looks like this (simplified):

IDE redefinition -> pass [new class] -> JVM ->
HotswapTransformer.transform() -> OsgiEquinoxPlugin.reload()

(transformed code from HotswapTransformer.transform() is returned to JVM
which redefines the class at last.)

Osgi plugin writes the content of redefined file to extraClasspath,
therefore it is *not necessary to synchronizeextraClasspath from IDE*
(check it if you do that,
may be it can be the problem).

regards vladimir

2017-10-09 16:13 GMT+02:00 Bastien BARET <notifications@github.com>:

**Comment by skybber** [comment]
fixed
