### ISSUE TITLE
ERROR (org.hotswap.agent.watch.nio.EventDispatcher) - No match for watch event

### ISSUE THREAD

**Issue by ThueGram-Hansen** [HotswapProjects/HotswapAgent#223]
Hi Hotswap agents,

thanks for a great plugin! However, I'm experiencing some issues I hope you can help me resolve. I've got:
•	Java v. 1.8.0_144 
•	Spring 4.2.3 multi module system 
•	running on Apache Tomcat (TomEE)/7.0.62 (1.7.2)
and the hotswap agent plugin Version: 1.2 installed through IntelliJ 2016.3.7 Unlimited. The plugin is working well for hotswapping java classes, but an error messages is constantly printed as output, after application deployment:

`HOTSWAP AGENT: 15:08:43.469 ERROR (org.hotswap.agent.watch.nio.EventDispatcher) - No match for  watch event 'sun.nio.fs.AbstractWatchKey$Event@58f34039',  path '...\tomee\apache-tomee-plume-1.7.2\logs\core.log'`

I've tried various hotswap-agent.properties, but can't seem to ignore the tomee .log files. 

I’m also not able to hot swap resources. I’ve tried multiple paths for the watchResources property, but it still doesn’t seem to work. As I said, there are quite a few modules and therefore also different resource folders, so I’m unsure about the correct approach. Hope you can help me swapping it like it hot, and keep up the excellent work.

Best regards

**Comment by edudant** [comment]
Can you please create a sample project in https://github.com/HotswapProjects/HotswapAgentExamples repo?

**Comment by edudant** [comment]
TreeWatcherNIO registered events in parent directory instead of actual directory. Solved.
