### ISSUE TITLE
Newly created classes cannot participate in HotSwap

### ISSUE THREAD

**Issue by DonatasC** [HotswapProjects/HotswapAgent#225]
I can (successfully) start HotSwap debug session with IntelliJ IDEA and HotSwap Agent. Modifications of existing code are being picked-up and work OK. 
But if I create NEW class and build it, I cannot reference it - JVM reports ClassNotFound.

**Comment by edudant** [comment]
Hi - new class is not loaded by debugging session (as class modification), but via stadnard classloading. Is your class compiled on classpath? You can use [extraClasspath property](http://hotswapagent.org/mydoc_configuration.html).
