### ISSUE TITLE
Eclipse IDE failed to create JVM

### ISSUE THREAD

**Issue by FiruzzZ** [HotswapProjects/HotswapAgent#249]
after replacing by DCEVM I can't run Eclipse anymore if I execute eclipse.exe says: "Failed to create the JVM"; if I run eclipsec.exe it opens a cmd saying: Must use the serial GC in the DCEVM
JDK and DCEVM versions are 1.8_172

**Comment by skybber** [comment]
it's definitively dcevm (installation) issue - not HotswapAgent.
