### ISSUE TITLE
i18n properties in JSF project on IntelliJ

### ISSUE THREAD

**Issue by arthurgregorio** [HotswapProjects/HotswapAgent#260]
Im trying to make hotswap agent 1.3 + dcevm on JDK 8u172 reload my i18n properties files after the edition process on intellij but until now, no way to make this thing work...

I defined the propoerties on the agent properties file but i don't know if the way i do  will work:

```java
watchResources=${project.root}/src/main/resources;
extraClasspath=${project.root}/target/classes;
```

I tryed to do in the same way like jrebel, but no hotswap for i18n properties... The project root variable is replaced by the maven resources pluign when i build the project and is a direct reference to the ${basedir} variable from maven..

Any advice?

**Comment by skybber** [comment]
It should work. I have no issue with it. Properties reloading is done both in Mojarra and MyFaces plugins. What app server are you using?

**Comment by arthurgregorio** [comment]
i'm using wildfly 13

Is there any way to see if the file is being picked-up by the hotswap agent? 

In jrebel, for example, we have a info on the log saying "the file xyz is being reloaded on path/of/the/file"

**Comment by skybber** [comment]
You can activate debug level for Mojarra plugin in hotswap-agent.properties. Then you should see [this](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-mojarra-plugin/src/main/java/org/hotswap/agent/plugin/mojarra/MojarraPlugin.java#L72) , but you won't ! The implementation for resources reloading is still missing for [wildfly](https://github.com/HotswapProjects/HotswapAgent/tree/master/plugin/hotswap-agent-jbossmodules-plugin). I'm looking for someone to cooperate on this. I can help with this issue, but I don''t use the wildfly!

**Comment by skybber** [comment]
If you are still interested, please can contact me by email.

**Comment by arthurgregorio** [comment]
Yes, i'll send a message.

Just for better understanding:

The wildfly plugin doesn't support reload any resource of JSF like managed beans, i18n resources? CDI beans with ```@Named``` can be reloaded by hotswap agent on wildfly?

**Comment by skybber** [comment]
Should be fixed in 1.3.1.SNAPSHOT.

**Comment by skybber** [comment]
Could you check it please?

**Comment by arthurgregorio** [comment]
I will try, when you are planning to launch the 1.3.1-SNAPHOT?

**Comment by skybber** [comment]
We have no deadlines, but it shouldn't be this year :) Btw I'm updating SNAPSHOTs continuously

**Comment by skybber** [comment]
I§ve meant the  (1.3.1-SNAPSHOT)[https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.3.1-SNAPSHOT] is updated continuously, so could you check it please?
