### ISSUE TITLE
OpenJDK 10 + HotswapAgent 1.3 + WildFly 13 works but prints error

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [HotswapProjects/HotswapAgent#264]
Hello, I'm adding methods, and it works. But in the log it shows error:

15:11:40,260 INFO  [stdout] (default task-1) HOTSWAP AGENT: 15:11:40.260 INFO (org.hotswap.agent.plugin.wildfly.el.WildFlyELResolverPlugin) - Patched org.jboss.el.cache.BeanPropertiesCache

15:11:40,263 INFO  [stdout] (default task-1) HOTSWAP AGENT: 15:11:40.263 INFO (org.hotswap.agent.plugin.wildfly.el.WildFlyELResolverPlugin) - Patched org.jboss.el.cache.BeanPropertiesCache$SoftConcurrentHashMap

15:13:04,126 INFO  [stdout] (Thread-510) HOTSWAP AGENT: 15:13:04.125 INFO (org.hotswap.agent.plugin.wildfly.el.PurgeWildFlyBeanELResolverCacheCommand) - Cleaning  BeanPropertiesCache siapen.bean.ServerBean ModuleClassLoader for Module "deployment.siapenweb.war" from Service Module Loader.

15:13:04,313 INFO  [stdout] (Thread-511) HOTSWAP AGENT: 15:13:04.308 ERROR (org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand) - Error reloadBean class siapen.bean.ServerBean in classLoader ModuleClassLoader for Module "deployment.siapenweb.war" from Service Module Loader
15:13:04,315 INFO  [stdout] (Thread-511) java.lang.reflect.InvocationTargetException

15:13:04,317 INFO  [stdout] (Thread-511) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

15:13:04,318 INFO  [stdout] (Thread-511) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

15:13:04,321 INFO  [stdout] (Thread-511) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

15:13:04,328 INFO  [stdout] (Thread-511) 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

15:13:04,329 INFO  [stdout] (Thread-511) 	at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.reloadBean(BeanClassRefreshCommand.java:151)

15:13:04,330 INFO  [stdout] (Thread-511) 	at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.executeCommand(BeanClassRefreshCommand.java:88)

15:13:04,331 INFO  [stdout] (Thread-511) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)

15:13:04,331 INFO  [stdout] (Thread-511) Caused by: java.lang.NoClassDefFoundError: org/jboss/weld/context/ContextNotActiveException

15:13:04,337 INFO  [stdout] (Thread-511) 	at java.base/java.lang.Class.forName0(Native Method)

15:13:04,339 INFO  [stdout] (Thread-511) 	at java.base/java.lang.Class.forName(Class.java:374)

15:13:04,343 INFO  [stdout] (Thread-511) 	at deployment.siapenweb.war//org.hotswap.agent.plugin.weld.command.BeanClassRefreshAgent.reloadBean(BeanClassRefreshAgent.java:183)

15:13:04,345 INFO  [stdout] (Thread-511) 	... 7 more

15:13:04,345 INFO  [stdout] (Thread-511) Caused by: java.lang.ClassNotFoundException: org.jboss.weld.context.ContextNotActiveException from [Module "org.jboss.weld.core" version 3.0.4.Final from local module loader @d2de489 (finder: local module finder @14bdbc74 (roots: K:\wildfly-13.0.0.Final\modules,K:\wildfly-13.0.0.Final\modules\system\layers\base))]

15:13:04,345 INFO  [stdout] (Thread-511) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)

15:13:04,345 INFO  [stdout] (Thread-511) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)

15:13:04,346 INFO  [stdout] (Thread-511) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)

15:13:04,347 INFO  [stdout] (Thread-511) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)

15:13:04,353 INFO  [stdout] (Thread-511) 	... 10 more

15:13:04,431 INFO  [stdout] (Thread-511)

**Comment by skybber** [comment]
Could you check https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.3.1-SNAPSHOT please?

**Comment by BryanV91** [comment]
> Could you check https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.3.1-SNAPSHOT please?

It is working and no longer giving errors in console.

**Comment by skybber** [comment]
thanks.
