### ISSUE TITLE
Disable a plugin ?

### ISSUE THREAD

**Issue by gochev** [HotswapProjects/HotswapAgent#266]
Hello everyone,

how can I disable the spring plugin ? 
It doesnt seems to work for real not hello world projects and I actually dont need it since I am using mostly XML configurations which are not supported anyway.

Right now the app even cant start with this plugin ;)

**Comment by skybber** [comment]
`-javaagent: .... hotswap-agent-1.3.0.jar=disablePlugin=Spring`

**Comment by gochev** [comment]
thanks ! :)
