### ISSUE TITLE
basePackage '#anyPackage' not associated with any scannerAgent

### ISSUE THREAD

**Issue by MrABKhan** [HotswapProjects/HotswapAgent#272]
When ever using HotswapAgent with JBoss and with my spring jars to be as Jboss Modules then I get this error.
ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - basePackage 'com.journaldev.spring' not associated with any scannerAgent

and then Autowiring stops working after this.

**Comment by skybber** [comment]
What version java/spring?

**Comment by MrABKhan** [comment]
Spring : 4.3.9.RELEASE
Java : 1.8.0_181
