### ISSUE TITLE
Unnecessary logs when pluginPackages is used on JDK11

### ISSUE THREAD

**Issue by theigl** [HotswapProjects/HotswapAgent#276]
Issues with `extraClasspath` have been resolved in #274 but logging issues still remain when `pluginPackages` is specified. This can be reproduced with the demo attached to #274. 

My own application logs dozens of these statements during startup and hundreds more when I start using it:

    HOTSWAP AGENT: 10:52:45.294 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: []
    HOTSWAP AGENT: 10:52:45.297 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: []
    HOTSWAP AGENT: 10:52:45.300 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: []

**Comment by skybber** [comment]
Hi, HA just skips DelegatingClassLoader which could improve startup time, thanks for report.
