### ISSUE TITLE
xhtml not swapped

### ISSUE THREAD

**Issue by krizajb** [HotswapProjects/HotswapAgent#277]
This is a redirected bug form [here](https://github.com/dmitry-zhuravlev/hotswap-agent-intellij-plugin/issues/26).

Any ideas why .xhtml changes aren't updated? Working with wildfly 14 and maven using InteliJ Idea. I deploy .ear:exploded. If I change and recompile .java file, the change is swapped. No luck with .xhtml tho :/

**Comment by skybber** [comment]
webAppDir for wildfly is on my TODO List, but it should work if you use Myfaces/Mojarra (JSF) even without HA.

**Comment by krizajb** [comment]
Any tips where to look for that?

**Comment by skybber** [comment]
Have you following fragment in web.xml (this is basic devel configs for JSF)?

```
  <context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Development</param-value>
  </context-param>

  <context-param>
    <param-name>javax.faces.FACELETS_REFRESH_PERIOD</param-name>
    <param-value>1</param-value>
  </context-param>
```

**Comment by skybber** [comment]
There is new HA undertow plugin supporting webappDir config property.
https://github.com/HotswapProjects/HotswapAgent/commit/7d7c57f8ac051ecc933cce1d1c884ed62bc7f43f
