### ISSUE TITLE
jdk 11 - WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by ming871** [HotswapProjects/HotswapAgent#283]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.hotswap.agent.util.ReflectionHelper (file:/Library/Java/JavaVirtualMachines/dcevm-11.0.1/Contents/Home/lib/hotswap/hotswap-agent.jar) to method com.sun.beans.WeakCache.put(java.lang.Object,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of org.hotswap.agent.util.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by ming871** [comment]
I'm using "trava-jdk-11-dcevm" : https://github.com/TravaOpenJDK/trava-jdk-11-dcevm

**Comment by ming871** [comment]
Yes, When I change "test.Test1();" to "test.Test2();", these warnings was shown.

**Comment by skybber** [comment]
Thanks, it looks like HotswapAgent problem on j11. I'll look at it.

**Comment by ming871** [comment]
Thanks reply, There is another issues: #284, please help.

**Comment by skybber** [comment]
After hotswap main() method is running old code - it is how the dcevm should work and is quite OK.
