### ISSUE TITLE
dcevm 8 and dcevm 11 reload success, but System.out not change.

### ISSUE THREAD

**Issue by ming871** [HotswapProjects/HotswapAgent#284]
CODE:

public class Main {

    public static void main(String[] args) throws Exception {
        Test test = new Test();
        while (true){
            test.Test1();
            Thread.sleep(1000);
        }
    }

    public static class Test{

        public void Test1(){
            System.out.println("---Test1-");
        }

        public void Test2(){
            System.out.println("---Test2-");
        }

    }
}

After I compile and run this,  I change the source "test.Test1();" to "test.Test2();", HotswapAgent shown it's reload success, but the method "Test2" not called.

I'm testing on mac os dcevm8 with oracle jdk 1.8_181 and dcevm11 with trava-jdk-11-dcevm

**Comment by ming871** [comment]
below are logs:

/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
HOTSWAP AGENT: 20:02:34.761 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.3.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 20:02:35.233 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'sun.misc.Launcher$AppClassLoader@18b4aac2'.
HOTSWAP AGENT: 20:02:35.348 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, AnonymousClassPatch, ClassInitPlugin, WatchResources, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin]
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
---Test1-
HOTSWAP AGENT: 20:02:49.542 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.of.server.app.tank.Main$Test, com.of.server.app.tank.Main] (autoHotswap)
---Test1-
---Test1-

**Comment by ming871** [comment]
I have tried Hotswap agent 1.3.0 and Hotswap agent 1.3.1, dcevm 8 and dcevm 11,

when I change the output in method "Test.Test1", the output changed.

**Comment by skybber** [comment]
It should work at least for dcevm8. It passed a lot of tests, a lot of people including me are using it daily. Did you follow instructions on http://hotswapagent.org ?

**Comment by ming871** [comment]
Yes, I follow the instructions , I tried linux too,  Attach file can used to test.
[test.zip](https://github.com/HotswapProjects/HotswapAgent/files/2721177/test.zip)

**Comment by skybber** [comment]
I'm sorry, I din't catch it. This is quite OK. Since you're running in old method. It is not possible to change code of current method and continue with running in modified method - it makes sense... You must leave the old method, then next method call will be running in new code. Or you have to use debugger and breakpoint which automatically drops to frame.

**Comment by ming871** [comment]
I misunderstand how it works, Thank you for your explanation.
