### ISSUE TITLE
Exception in WeldPlugin and Wildfly 16

### ISSUE THREAD

**Issue by dwehrle** [HotswapProjects/HotswapAgent#294]
Hi,

i get an exception starting Wildfly 16 with our application. With WF 15 it works. I use newest version from https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases.

19:24:47,889 INFO  [stdout] (MSC service thread 1) HOTSWAP AGENT: 19:24:47.889 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.weld.WeldPlugin' class 'org/jboss/weld/bean/proxy/ProxyFactory'.
19:24:47,889 INFO  [stdout] (MSC service thread 1) java.lang.reflect.InvocationTargetException

19:24:47,889 INFO  [stdout] (MSC service thread 1) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:213)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:107)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:214)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)

19:24:47,902 INFO  [stdout] (MSC service thread 1) 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.Module.loadModuleClass(Module.java:731)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.bean.builtin.ee.AbstractEEBean.<init>(AbstractEEBean.java:36)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.module.jta.UserTransactionBean.<init>(UserTransactionBean.java:52)

19:24:47,903 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.module.jta.WeldTransactionsModule.preBeanRegistration(WeldTransactionsModule.java:46)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.module.WeldModules.preBeanRegistration(WeldModules.java:158)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:224)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:438)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.weld.core@3.1.0.Final//org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:86)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.as.weld@16.0.0.Final//org.jboss.as.weld.WeldStartService.start(WeldStartService.java:97)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.msc@1.4.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.msc@1.4.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.msc@1.4.5.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at java.base/java.lang.Thread.run(Thread.java:834)

19:24:47,904 INFO  [stdout] (MSC service thread 1) Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] toClass(org.jboss.classfilewriter.ClassFile,java.lang.Class,org.jboss.weld.serialization.spi.ProxyServices,java.security.ProtectionDomain) not found in org.hotswap.agent.plugin.weld.command.ProxyClassLoadingDelegate

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.expr.MethodCall.replace(MethodCall.java:257)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.plugin.weld.transformer.ProxyFactoryTransformer$2.edit(ProxyFactoryTransformer.java:93)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.expr.ExprEditor.loopBody(ExprEditor.java:197)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.expr.ExprEditor.doit(ExprEditor.java:96)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.CtBehavior.instrument(CtBehavior.java:744)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.plugin.weld.transformer.ProxyFactoryTransformer.patchProxyFactory(ProxyFactoryTransformer.java:89)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	... 37 more

19:24:47,904 INFO  [stdout] (MSC service thread 1) Caused by: compile error: toClass(org.jboss.classfilewriter.ClassFile,java.lang.Class,org.jboss.weld.serialization.spi.ProxyServices,java.security.ProtectionDomain) not found in org.hotswap.agent.plugin.weld.command.ProxyClassLoadingDelegate

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:723)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.TypeChecker.atVariableAssign(TypeChecker.java:274)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.TypeChecker.atAssignExpr(TypeChecker.java:243)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.ast.AssignExpr.accept(AssignExpr.java:43)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:360)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.compiler.Javac.compileStmnt(Javac.java:578)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	at org.hotswap.agent.javassist.expr.MethodCall.replace(MethodCall.java:251)

19:24:47,904 INFO  [stdout] (MSC service thread 1) 	... 42 more

19:24:47,904 INFO  [stdout] (MSC service thread 1) 

Kind regards,
Daniel

**Comment by skybber** [comment]
The problem should be fixed now at:
https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.3.1-SNAPSHOT
I didn't have enough of time to test it properly on Wildfly16. Could you check it please? I didn't update the Trava release, so you should replace the integrated HA there.

**Comment by dwehrle** [comment]
Exception no longer exists.

Thank you!
