### ISSUE TITLE
HotswapAgent works with Spring 5.x?

### ISSUE THREAD

**Issue by ismaelgomescosta** [HotswapProjects/HotswapAgent#295]
HotswapAgent works with Spring 5.x?

**Comment by skybber** [comment]
It sould, you can try it with j11:
https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-spring-plugin/run-tests.sh

**Comment by ismaelgomescosta** [comment]
I'll try, thanks
