### ISSUE TITLE
WatchHandler.registerResource does not work as expected

### ISSUE THREAD

**Issue by envas** [HotswapProjects/HotswapAgent#298]
I am writing a custom plugin for the framework, where I have no access to the framework source code. Each jar file (aka module) has its own class loader instance and the class loader is not the URLClassLoader. So I transformed the framework's class loader to implement the interface HotswapAgentClassLoaderExt. 

WatchResourcePlugin works fine with resource files (@OnResourceFileEvent), however, the class file changes (@OnClassFileEvent) are ignored. I tracked down the events and discovered, that in my case the class file events are not registered on the WatchHandler. What I do not understand is this comment in the method `registerResources``

```java
        // classpath resources (already should contain extraClasspath)
        Enumeration<URL> en = classLoader.getResources(path);
```

This is based on the assumption, that getResources(String) invocation match all classpath entries that are directories, when given a resource name of "" or "."? But I think it is only valid for the URLClassLoader. My class loader is not a subclass of the URLClassLoader, anyway, it implements HotswapAgentClassLoaderExt. This, in turn, installs the WatchResourcesClassLoader as the loader responsible for loading resources. And WatchResourcesClassLoader.getResources does not return extraClasspath.

**Comment by skybber** [comment]
What about :

* extend HotswapAgentClassLoaderExt by `getExtraClassPath` method
* use it in `registerResources`

does it make sense in your case?

**Comment by envas** [comment]
It should work but `registerResources` is Hotswapagent internal API (is even private) so I cannot do it without changing the source code of the Hotswapagent framework core.

I must change anything in the code that is under my control like to transform getResources() in my ModuleClassLoader to return the extraClasspath as expected by `registerResources`. However, here is another problem - HotswapperPlugin is discovered before my Plugin and I have no chance to pass the extraClasspath to my ModuleClassLoader instance before `registerResources` is called. Can I define the order for the plugin initialization?

BTW because I have so much ModuleClassLoader instances without plugin configuration I get a lot of logger message `Discovered plugins: []`, I think the scanner should report only class loaders with successfully discovered Plugins, anything like this.

```java
if (discoveredPluginNames.size() > 0) {
    LOGGER.info("Discovered plugins: {}.", Arrays.toString(discoveredPluginNames.toArray()));
}
```

**Comment by skybber** [comment]
Did you try jbossmodules-plugin ? There is solved extraClassPath :

   https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-jbossmodules-plugin/src/main/java/org/hotswap/agent/plugin/jbossmodules/ModuleClassLoaderTransformer.java

As far as plugin initialization there is no priority handling now. 
As far as discovered plugins, there is a problem with child classloader which has unitialized parent classloader. So there is fallback method ensureClassLoaderInitialized in HotswapTransformer that initialized all found classloaders (except delegating).

**Comment by skybber** [comment]
What is the current status of your problem?

**Comment by envas** [comment]
I modified the HotswapAgent source code to match my needs.

**Comment by skybber** [comment]
Is it possible to publish your solution into HotswapAgent codebase or is it too specific?

**Comment by envas** [comment]
I must have a look into my code, I am not sure but maybe I am using any API from my framework.

**Comment by envas** [comment]
I checked my source code, basically, I made one change in `WatchHandler.registerResources` - I register only resources from my configuration (`config.getExtraClasspath`). My resources are packed into jar files and loaded with JarClassLoader, this is impossible to reload. My config extra classpath points to IDE build directories. This works fine for me. 

```
       // classpath resources (already should contain extraClasspath)
        // Enumeration<URL> en = classLoader.getResources(path);
        PluginConfiguration config = pluginManager.getInstance().getPluginConfiguration(classLoader);
        URL[]               urls   = config.getExtraClasspath();

        // while (en.hasMoreElements()) {
        for (URL url : urls) {

            try {

                // URI uri = en.nextElement().toURI();
                URI uri = url.toURI();

```

**Comment by skybber** [comment]
Since you have find solution, I will not extend `HotswapAgentClassLoaderExt` API to keep it simple. I'm closing this.
