### ISSUE TITLE
Can jars be hotswapped?

### ISSUE THREAD

**Issue by ninja-** [HotswapProjects/HotswapAgent#306]
I am working with an app that supports a plugins/ folder with .jar files inside.
Is it possible to get it working with autoHotswap or only .class files are supported? (haven't checked)
One of the issues here is that JVM is caching jar files in memory so by swapping jar files at runtime you can get segfault unless you disable the caching with a prop etc.

**Comment by skybber** [comment]
It's possible and described in docs - [extraClasspath](http://hotswapagent.org/mydoc_configuration.html)

**Comment by ninja-** [comment]
@skybber alright just got it working, so the key is to have a seperate extraClasspath for each of the plugins and each having its own hotswapper-agent.properties. thanks!
