### ISSUE TITLE
hotswap agent Not loading, seeing changes 

### ISSUE THREAD

**Issue by mtwallach** [HotswapProjects/HotswapAgent#319]
I have a project with Hotswap-agent that deploys into docker container running Centos. I'm running on Mac with Mac Docker Desktop and hot reloading works. When I execute mvn compile on my project, the Hotswap-agent picks up changes, I see the:
HOTSWAP AGENT: 14:10:29.887 DEBUG (org.hotswap.agent.watch.nio.WatcherNIO2) - Watch event 'ENTRY_MODIFY' messages, etc

I take same project and run on Windows 10, Windows Docker Desktop and changes are not being reloaded. I do not see WatcherNIO2 messages. I can see in docker container that reloading directories are mapped properly and I do see on startup of my project that org.hotswap.agent.watch.nio.WatcherNIO2 seems to be registering directories to be watched.
Any suggestions how to debug as to why my updated classes are not being seen by HotswapAgent?

**Comment by skybber** [comment]
Probably you know https://github.com/HotswapProjects/hotswap-docklands .  Did you try:

     -v /var/run/docker.sock:/var/run/docker.sock

**Comment by mtwallach** [comment]
i need to use HotswapAgent as it is part of guidance in some other project I'm working with. I'm running with docker-compose but I did try putting /var/run/docker.sock:/var/run/docker.sock as a volume. Still does not work.

Issue seems to be the project is not detecting change. I do not see any messages like:
 HOTSWAP AGENT: 14:10:29.887 DEBUG (org.hotswap.agent.watch.nio.WatcherNIO2) - Watch event 'ENTRY_MODIFY' on......

**Comment by skybber** [comment]
I think file change notifications is docker problem on Windows. It is working on Linux. As I remember we had this problem in the past but I don't know if there is solution for it (I've supposed the docker.sock had solved it, but it didn't as you have found).

**Comment by mtwallach** [comment]
Thanks for suggestion. I was able to have hotswap agent work properly with docker-for-windows-watch-bindings.html
