### ISSUE TITLE
Open JDK 10 support

### ISSUE THREAD

**Issue by prtsh716** [HotswapProjects/HotswapAgent#322]
please let me know how i would able to implement this on open jdk 10 ?

**Comment by skybber** [comment]
We didn't release dcevm10, but dcevm 11 you can find at

https://github.com/TravaOpenJDK/trava-jdk-11-dcevm

HA supports j11 since 1.3.1:

https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.3.1-SNAPSHOT
