### ISSUE TITLE
Mybatis resource not reloading

### ISSUE THREAD

**Issue by bpracht** [HotswapProjects/HotswapAgent#323]
This is my post from stackoverflow:
https://stackoverflow.com/questions/57876604/resource-file-not-reloading

My goal is to substitute JRebel with DCEVM/Hotswap for a Tomcat project built with Maven. I believe it is detecting my class file changes and handling them appropriately. However, it is not detecting resource changes. It's likely I configured it wrong, but I just don't know how. I'd like DCEVM/HotAgent built binaries as one block (classes + resources), rather than just classes.

I started with the assumption that it would load everything that the JVM normally would. Next, I added a hotswap-agent.properties file, and have not gotten that to work either.

hotswap-agent.properties
```
extraClasspath=
watchResources=src/main/resources
LOGGER=debug
```
I also tried watchResources= and watchResources=true

It's not clear to me what the format of "watchResources" should be.
For IP reasons, I cannot paste the full log file in a public forum, but did see this:

```
HOTSWAP AGENT: 14:21:27.546 DEBUG (org.hotswap.agent.util.classloader.WatchResourcesClassLoader) - Watching directory 'file:/C:/Software/src/main/resources' for changes.
HOTSWAP AGENT: 14:21:27.547 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory target C:\Software\src\main\resources via watched: C:\Software\src\main\resources
HOTSWAP AGENT: 14:21:27.547 DEBUG (org.hotswap.agent.watch.nio.TreeWatcherNIO) - WATCHING: ENTRY_CREATE, ENTRY_DELETE, ENTRY_MODIFY - fileTree,high C:\Software\src\main\resources
```

Interestingly, my files are not under C:\Software\src\main\resources, but rather something like C:\Repos\myproject\src\main\java and c:\Repos\myproject\src\main\resources.

If it matters, the resource is a MyBatis mapper XML file. If I can get this to treat the mapper file as any other resource that be reloadable, that would be good. I know JRebel was able to handle this, so conceptually I'm sure DCEVM/HotAgent could do the same. 

I'd like some message that says it detected a change in the resource and an appropriate message.

**Comment by bpracht** [comment]
I also tried adding ${basedir} to the watch properties, but it's not substituting the variable, instead choosing to treat it as a literal portion of the directory.
```
watchResources=${basedir}/src/main/resources
```
Gets treated like 
c:\Software\${basedir}/src/main/resources

**Comment by skybber** [comment]
watchResources doc you can find [here](http://hotswapagent.org/mydoc_configuration.html), myBatis reloding is still not supported in HotswapAgent, look at https://github.com/HotswapProjects/HotswapAgent/issues/86

**Comment by bpracht** [comment]
I got what I wanted, and unless I'm creating a new mapping file, things
work. But the variable substitution like basedir does not work. Instead, I
have to use a fully qualified path name.

Regards,
Ben

**Comment by skybber** [comment]
Did you find some solution how to reload SqlSessionFactory configuration? There is experimental MyBatis plugin in HotswapAgent now, but it need more work since MyBatis has very flexible configuration mechanism, it is not easy to solve all variants.

**Comment by skybber** [comment]
Should be solved by myBatis plugin
