### ISSUE TITLE
hotswap agent core 1.4 jar missing?

### ISSUE THREAD

**Issue by FiruzzZ** [HotswapProjects/HotswapAgent#338]
Since the release of Agent 1.4.0 there is no more hotswap-agent-core.jar with it, this is intentional? we don't need it anymore? or we still need it?
I know it can be found in Maven repository

**Comment by skybber** [comment]
There is one on maven central:

https://mvnrepository.com/artifact/org.hotswapagent/hotswap-agent-core/1.4.0

If you are using dcevm11, then HotswapAgent is integrated within TravaOpenJDH distribution as an uberJAR.
