### ISSUE TITLE
IDEA does not recognize the bundled dcevm from trava-jdk-11-dcevm

### ISSUE THREAD

**Issue by gatanaso** [HotswapProjects/HotswapAgent#340]
Hi,

First of all, thank you very much for this project 🙏  

I have been trying to use trava-jdk-11-dcevm (https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/tag/dcevm-11.0.6%2B1), but have stumbled into an issue with the IDEA HotSwapAgent plugin. 

The plugin does not recognize the DCEVM that comes bundled with the JDK and it shows the following message:

![Screen Shot 2020-03-09 at 13 17 21](https://user-images.githubusercontent.com/15094658/76208443-5a273200-6208-11ea-831b-9b5f4b2af519.png)

Is there a way to tell the plugin to use the dcevm that comes bundled with the JDK?

Kind regards,
Goran

**Comment by skybber** [comment]
I'm not expert on Idea, but I you don't need to use explicit plugin+configuration at all. HA could be found automatically by JVM. Only configuration I'm using on Eclipse is: ` -Xlog:redefine+class*=info -XX:+UseConcMarkSweepGC`  , both parameters are optional.

**Comment by gatanaso** [comment]
@skybber Thank you for the very prompt reply, I will try your suggested approach.
