### ISSUE TITLE
JAXB annotations support ?

### ISSUE THREAD

**Issue by michelsaumon** [HotswapProjects/HotswapAgent#344]
Hi,

I have some classes annotated with JAXB annotations, like `javax.xml.bind.annotation.XmlElement`.
Hot reload does not seem to work.

Is this supported ?

I'm in a JDK 8 / Wildfly 10 environnement, and I use version 1.4.1 of the agent.

Thanks !

**Comment by skybber** [comment]
JAXB is not supported now. Has Wildfy reference implementation of JAXB or some proprietary one?

**Comment by michelsaumon** [comment]
Ok, thanks.

Don't know really, should be Resteasy in my use case : 
resteasy-jaxb-provider-3.0.19.Final.jar

But if I'm not wrong there also an implementation in Java SE 8.

Can you tell me if JAXB support is planned in a future release ?

**Comment by skybber** [comment]
It's not planned now
