### ISSUE TITLE
Spring Versioning Strategy

### ISSUE THREAD

**Issue by ruediste** [HotswapProjects/HotswapAgent#349]
What is the versioning strategy regarding Spring? Currently the spring plugin depends on Spring 4.3.2.RELEASE. I would like to use it 5.2.6.RELEASE. Should I update the dependency? This would run the unit tests on that version. Should support for 4.3 be dropped? If not, how would it be tested for regressions going forward?

**Comment by skybber** [comment]
It should be backward compatible as much as possible. We have version tests at: https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-spring-plugin/run-tests.sh 
May be Jiri could tell more about SpringPlugin.

**Comment by edudant** [comment]
Definitely old versions should be supported. It is quite chalenging, because there is lot of changes between versions. In the future we consider split implementation into multiple plugins, separate plugin for each version. Currently you may upgrade SpringPlugin to the new version, develop it and then run all backwards tests.

**Comment by ruediste** [comment]
Ok, that'll work.

**Comment by ruediste** [comment]
I continued working on my Spring MVC Bugfix. I tried running the backwards tests and had some issues with the really old versions. I had a look at the [supported versions](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#supported-versions):

> - 4.3.x is the last feature branch of the 4th generation. It comes with extended maintenance until April 2020 and critical patches even beyond that point. 4.3.x will reach its official EOL (end-of-life) on December 31st, 2020.
> 
> - 3.2.x is EOL (end-of-life) as of December 31st, 2016. No further maintenance releases and security patches are planned in that line. Please migrate to 4.3 or 5.x at your earliest convenience!

With that background i propose to drop support for all pre-4.3 versions. What do you think?

**Comment by edudant** [comment]
From my point of view it is much more important to have working plugin for new version then to support obsolete versions. Please drop old version support, and only if anyone has time for it, we may reconsider.

**Comment by ruediste** [comment]
Implemented in pull request #350
