### ISSUE TITLE
Spring MVC support (@RequestMapping)

### ISSUE THREAD

**Issue by agentgt** [HotswapProjects/HotswapAgent#35]
I think HotswapAgent does not support reloading `@RequestMapping` routes in beans.

I think all that needs to be done is on a bean change with a `@RequestMapping` annotation is look in the `ApplicationContext` for all derivations of `AbstractUrlHandlerMapping` and call `initApplicationContext()`.

You could reload the HandlerMapping beans but you can't just clear the HashMaps in them as the the URLs are only calculated on initialization. You also can't call `setApplicationContext` as that will think nothing has changed.

I'll look into trying the above unless others have thoughts?

**Comment by skybber** [comment]
fixed by  @frankdavid
