### ISSUE TITLE
Question: Determining whether classes will be reloaded 

### ISSUE THREAD

**Issue by joheriks** [HotswapProjects/HotswapAgent#354]
As a plugin author, I would like to know programmatically whether HotswapAgent will dynamically reload classes. I.e., if running in debug mode from an IDE or the `autoHotswap` property is set to true. Is there an API for determining this?

**Comment by skybber** [comment]
`autoHotswap` flag is accessible using `HotswapAgent.isAutoHotswap()`, not sure how to test debug mode. Dou you need it for non HA JVM mode ?

**Comment by joheriks** [comment]
Basically looking for a way to access the logic that HotswapAgent uses to determine whether it should track class file changes and reload dynamically into the JVM. It would only be needed when HotswapAgent is running as javaagent, and the purpose would be to alert the user when hotswapping may not be available.

**Comment by skybber** [comment]
Instrumentation inside HA always patches `@Transformer` classes seen by JVM as I know and can't be turned off globally if HA is used as an agent. ... its not very nice if jdk with integrated HA is intended to be used as a standard jdk.

**Comment by joheriks** [comment]
Thanks for the insights. I believe this is outside the scope of HA and should be handled by the front-end (in this case Vaadin devmode) checking for the absence of JPDA and `HotswapAgent.isAutoHotswap()==false`. Closing the ticket.
