### ISSUE TITLE
Jsf ManagedBean annotation support

### ISSUE THREAD

**Issue by sinanyumak** [HotswapProjects/HotswapAgent#363]
Hello,

I ve modified jsf plugins to add ManagedBean annotation support. I would be happy to send a pull request if you re interested in.

Hoping you a good day :)

**My Repository:**
https://github.com/sinanyumak/HotswapAgent

**Plugins:**
hotswap-agent-myfaces-plugin
hotswap-agent-mojarra-plugin

**Features:**
Reloading of ManagedBean annotations. (ManagedProperty annotation works also.)
Registering new ManagedBean s to bean context.

**Comment by skybber** [comment]
Great! Please do it.
