### ISSUE TITLE
how to enabled hotswap on java SE and maven?

### ISSUE THREAD

**Issue by FiruzzZ** [HotswapProjects/HotswapAgent#368]
before HotswapAgent had a repository in Maven, we have to add VM Options like:
`-XXaltjvm=dcevm
 -javaagent:D:/libs/hotswap-agent.jar`
Now we can add it as a dependency, 
```
<dependency>
            <groupId>org.hotswapagent</groupId>
            <artifactId>hotswap-agent</artifactId>
            <version>1.4.1</version>
            <scope>test</scope>
```

if I remove `-javaagent:D:/libs/hotswap-agent.jar` doesn't work, how can/should I replace this hardcoded path?

**Comment by skybber** [comment]
I'm sorry for delay. It works without additinal argument only with integrated HotswapAgent on java11

**Comment by skybber** [comment]
Since dcevm11.0.9 there is new option[-XX:HotswapAgent](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm) specifying what kind of HA to use,
