### ISSUE TITLE
NoClassDefFoundError: sun/reflect/ReflectionFactory (JAX-RS Client + Mybatis)

### ISSUE THREAD

**Issue by dhaalves** [HotswapProjects/HotswapAgent#369]
The error occur whenever I try to call a JAX-RS endpoint on **Application A**,  using JAX-RS Client from **Application B**

- Both Applications are deployed on same server (Wildfly 18). 
- On the **Application A**, I have Mybatis dependency for DB operations
- Tested with: Dcevm-11.0.8+1 (2020-07-27), Dcevm-11.0.7+4 (2020-06-27),dcevm-11.0.8+1-staged, dcevm-11.0.7+4-staged. 
- If I let Hotswapagent disabled no error occur.

> Caused by: java.lang.NoClassDefFoundError: sun/reflect/ReflectionFactory
> 	at deployment.financeiro-api.war//org.hotswap.agent.plugin.mybatis.proxy.ConfigurationProxy.proxy(ConfigurationProxy.java:89)
> 	at deployment.financeiro-api.war//org.apache.ibatis.builder.xml.XMLConfigBuilder.<init>(XMLConfigBuilder.java:92)
> 	at deployment.financeiro-api.war//org.apache.ibatis.builder.xml.XMLConfigBuilder.<init>(XMLConfigBuilder.java:82)
> 	at deployment.financeiro-api.war//org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:77)
> 	at deployment.financeiro-api.war//org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:64)
> 	at deployment.financeiro-api.war//br.uel.ati.core.api.mybatis.SqlSessionFactoryProvider.produceFactory(SqlSessionFactoryProvider.java:27)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.jboss.weld.core@3.1.2.Final-redhat-00001//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
> 	... 110 more

**Comment by skybber** [comment]
Should be fixed now in 1.4.2-SNAPSHOT. I've updated release packages, could you please check it and let me know if it helps?
