### ISSUE TITLE
LinkageError when used with Tomcat

### ISSUE THREAD

**Issue by achimmihca** [HotswapProjects/HotswapAgent#382]
I try to use the hot-swap feature on a multi-project Maven web app.
We use Tomcat as Servlet Container.

When I do a "Build > Rebuild Project" in IntelliJ, it is telling me "1 classes reloaded" in a green notification bubble. So far so good.
Yet, when I reload the webapp, I get the following Exception:

```
java.lang.LinkageError: loader constraint violation: when resolving method 'config.Config config.ConfigAccess.getConfig()' the class loader org.apache.jasper.servlet.JasperLoader @313b971e of the current class, org/apache/jsp/index_jsp, and the class loader org.apache.catalina.loader.ParallelWebappClassLoader @32d415e for the method's defining class, config/ConfigAccess, have different Class objects for the type config/Config used in the signature (org.apache.jsp.index_jsp is in unnamed module of loader org.apache.jasper.servlet.JasperLoader @313b971e, parent loader org.apache.catalina.loader.ParallelWebappClassLoader @32d415e; config.ConfigAccess is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @32d415e, parent loader java.net.URLClassLoader @5852c06f)
		at org.apache.jsp.index_jsp._jspService(index_jsp.java:129)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		...
```

### Sample project 

I prepeared a small project to reproduce this issue: https://github.com/achimmihca/HotSwapAgent-LinkageError-Tomcat

The repo contains two important files:
- Config.java is in project "lib-config" and provides access to some dummy configuration.
- index.jsp is in project "webapp-demo" and holds the content of the web page. It uses Config.java to say hello.

I make a change in Config.java, hotswap, reload the page, and then the error occurs.
I guess the new class definition is not propagated correctly through the running web app.

### JVM Version
I use Dcevm-11.0.9+1 (2020-10-24) from [over here](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases).
In IntelliJ I configured additional VM-argument for Tomcat "-XX:HotswapAgent=fatjar".

### Tomcat Plugin

My logs show

```
HOTSWAP AGENT: 16:02:57.885 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 16:02:58.042 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Starting HotswapAgent 'D:\java\dcevm-11.0.9+1\lib\hotswap\hotswap-agent.jar'

...

HOTSWAP AGENT: 16:02:59.037 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.tomcat.TomcatPlugin' initialized in ClassLoader 'ParallelWebappClassLoader
  context: webapp_demo_war_exploded
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@5852c06f
'.
HOTSWAP AGENT: 16:02:59.037 INFO (org.hotswap.agent.plugin.tomcat.TomcatPlugin) - Tomcat plugin initialized - Tomcat version '9.0.31.0'
```

So I guess the DECVM is started and I am also using Tomcat plugin.

### hotswap-agent.properties

I have a hotswap-agent.properties file where I added the compiled output location of classes from my plugins.

```
extraClasspath=\
  D:\\repos\\git\\HotSwapAgent-LinkageError-Tomcat\\webapp-demo\\..\\lib-config\\target\\classes;
  D:\\repos\\git\\HotSwapAgent-LinkageError-Tomcat\\webapp-demo\\target\\classes;
```

Note that the path is a little weird because I am using a Maven property, i.e. , `${project.basedir}\\..\\lib-config\\target\\classes;` and `${project.basedir}` points to the webapp-demo project instead of the root project.

Actually I am not sure if this is how the `extraClasspath` property is intended.
I only found [this page](http://hotswapagent.org/mydoc_plugin_tomcat.html) which does not say a lot.

As I understand, the new class file in `target/classes` folder should be used instead of the one that was packed in the jar file initially. How is this supposed to work?

### Conclusion

Am I missing some config, is it a bug, or is it a limitation of the DECVM hot-swap features?

Thanks!

**Comment by skybber** [comment]
`extraClasspath` is used by HA plugins for servlet containers (Tomcat, JBossModules, Glassfish etc.) to patch ClassLoaders. According logs there is some mess in ClassLoaders. HA does not patch JasperLoader (may be it should), I guess that ParallelClassLoader is trying to load redefined JSP classes, but it should be done by JasperLoader.

**Comment by achimmihca** [comment]
The only feature of HA that I am really interested in is adding/removing/changing lambda methods. This works in JSP and tag files (because Tomcat handles this).

But as soon as I want to write some stream API stuff (filter, map, reduce, sort, etc.) in normal a Java class, I have to build and re-deploy.

Is there any way to get this working with hotswap? Is there maybe a "light" version of HA that allows lambda hotswap and is more stable than "normal" HA?

**Comment by skybber** [comment]
Strange, I have no problems with lambdas on dcevm11.0.9. We have unit tests with lambdas an all of them are green :)

**Comment by achimmihca** [comment]
I mean in combination with Tomcat as given in the example project that I linked above.
I have no doubt that hotswapping lambdas and much more is possible with HA in many cases. But it failed in my specific setup.

I imagine (but don't know) that some mechanics implemented in HA are more complex than others, thus creating more potential for issues when combined with other software (e.g. Tomcat). 
Assuming this, I wonder if it would be possible to configure which hot-swap features are enabled (e.g. adding/removing fields, vs. only adding/removing lambdas) such that hotswap errors can be avoided by disabling some of them.

>  HA does not patch JasperLoader (may be it should), I guess that ParallelClassLoader is trying to load redefined JSP classes, but it should be done by JasperLoader.

Does this mean the issue would have to be fixed by Tomcat devs? Or maybe a new HA-Plugin to control JasperLoader would help?

**Comment by skybber** [comment]
It should be definitely fixed in HA-Plugin.

**Comment by achimmihca** [comment]
I just tried Payara Server as alternative to Tomcat. I get pretty much the same error:

```
java.lang.LinkageError: loader constraint violation: when resolving method 'config.Config config.ConfigAccess.getConfig()' the class loader org.apache.jasper.servlet.JasperLoader @fa0ab2d of the current class, org/apache/jsp/index_jsp, and the class loader org.glassfish.web.loader.WebappClassLoader @524d917 for the method's defining class, config/ConfigAccess, have different Class objects for the type config/Config used in the signature (org.apache.jsp.index_jsp is in unnamed module of loader org.apache.jasper.servlet.JasperLoader @fa0ab2d, parent loader org.glassfish.web.loader.WebappClassLoader @524d917; config.ConfigAccess is in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @524d917, parent loader org.glassfish.internal.api.DelegatingClassLoader @3447d3f2)
```

On the other hand, I guess if the issue is fixed for Tomcat, it might also work with other Servlet Containers, e.g., Payara

**Comment by skybber** [comment]
Thanks for help with this issue. Finally the problem was in dcevm. There is fix in new release https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/tag/dcevm-11.0.10%2B3 , could you confirm if it fixed the problem?

**Comment by achimmihca** [comment]
Yes, it seems to work now. Many thanks!
