### ISSUE TITLE
java.lang.NoSuchMethodException: org.hibernate.validator.internal.metadata.BeanMetaDataManager.__resetCache() when running springboot 2.3.0 project.

### ISSUE THREAD

**Issue by ghuser** [HotswapProjects/HotswapAgent#383]
I am getting the following exception on a springboot 2.3.0 project running in tomcat:

```
HOTSWAP AGENT: 02:44:26.522 ERROR (org.hotswap.agent.plugin.hibernate.HibernatePlugin) - Error refreshing BeanMetaDataManagerCache/AnnotatedMetaDataProvider cache.
java.lang.NoSuchMethodException: org.hibernate.validator.internal.metadata.BeanMetaDataManager.__resetCache()
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at org.hotswap.agent.plugin.hibernate.HibernatePlugin$1.executeCommand(HibernatePlugin.java:107)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
```

I use `dcevm-11.0.9+2` with [1.4.2-SNAPSHOT](https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.4.2-SNAPSHOT)

Note: Changed are applied when editing rest controllers.

**Comment by kdejaeger** [comment]
I have it as well, it's something that did not occur before (versions a few months ago).

**Comment by skybber** [comment]
Could you check if you have class org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvide in the project?

**Comment by ghuser** [comment]
In our case we have: 
    `org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.class` 
inside 
    `hibernate-validator-6.1.5.Final.jar`

**Comment by kdejaeger** [comment]
6.1.7 here. Comes with Spring boot.

**Comment by skybber** [comment]
Probably this class was removed. HA currently does not support Hibernate 6.x, so just only possible way ho to make it working is disabliing Hibernate plugin on start.
