### ISSUE TITLE
Exception in thread "Thread-4" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by lkakaka** [HotswapProjects/HotswapAgent#389]
```
public class TestDcevm {

    public void test(String s) {
        System.out.println(s);
    }
}

public class Main {
    public static void main(String args[]) {
        TestDcevm testDcevm = new TestDcevm();
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        testDcevm.test("hello");
                        Thread.sleep(10000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }
}
```

When the test function adds a parameter and reloads all classes, an exception will be thrown.
Exception in thread "Thread-4" java.lang.NoSuchMethodError: com.test.TestDcevm.test(Ljava/lang/String;)V
	at Main$1.run(Main.java:11)
	at java.lang.Thread.run(Thread.java:748)

The modified code looks like this:

```
public class TestDcevm {

    public void test(String s, int a) {
        System.out.println(s);
    }
}


public class Main {
    public static void main(String args[]) {
        TestDcevm testDcevm = new TestDcevm();
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        testDcevm.test("hello", 1);
                        Thread.sleep(10000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }
}

```

**Comment by skybber** [comment]
Thanks for report. It is less known limitation of current dcevm implementation. In this case, JVM is running in old bytecode, since hotswap mechanism does not swap current executing bytecode, that is all bytecodes of methods on callstack. New bytecode is used only in new calls. In your case, you are modifying main() method, but JVM is running in old bytecode, that calls method `test` with one argument, but a new method `test` has 2 arguments ! This problem is nearly impossible to fix, since old method must not be called due the layout of the object (new fields) could be changed.

**Comment by lkakaka** [comment]
> Thanks for report. It is less known limitation of current dcevm implementation. In this case, JVM is running in old bytecode, since hotswap mechanism does not swap current executing bytecode, that is all bytecodes of methods on callstack. New bytecode is used only in new calls. In your case, you are modifying main() method, but JVM is running in old bytecode, that calls method `test` with one argument, but a new method `test` has 2 arguments ! This problem is nearly impossible to fix, since old method must not be called due the layout of the object (new fields) could be changed.

Thansk for your answer. Does it mean that I can't change the method signature of the class which used in a running thread?

**Comment by skybber** [comment]
You can change it, but the actually running code(method you are staying in) is not changed. You must leave the method and reenter to see the changes.

**Comment by lkakaka** [comment]
> You can change it, but the actually running code(method you are staying in) is not changed. You must leave the method and reenter to see the changes.

Is it not thread-safe? when a funciton running in vm stack, then i change the signature of function which quoted by running function, it also thrown the exception. I simulate this situation as follows，First, i change the funciton signature of the TestDcevm class, then input ‘’next“,  it will throw NoSuchMethodError.
public class Main {
    static TestDcevm testDcevm = new TestDcevm();

    public static void main(String args[]) {
        ConsoleInput.addInputListener(Main::onInput);
         ConsoleInput.startInput();
        //  wait for ConsoleInput acquire the lock
        while (! ConsoleInput.isStart) {
            try {
                Thread.sleep(10);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        run();
    }

    public static void run() {
         // wait for ConsoleInput release the lock
         ConsoleInput.lock.lock();
        testDcevm.test("hello");
    }

    public static void onInput(String input) {
        switch (input) {
            case "next":
                // ConsoleInput release the lock
                 ConsoleInput.lock.unlock();
                break;
        }
    }

**Comment by skybber** [comment]
It has nothing to do with tread safety, VM continues in execution of old code from call stack, if new one is used for new calls, but there the limitation I was writing before.
