### ISSUE TITLE
Status of Seam 2 framework support?

### ISSUE THREAD

**Issue by stolp** [HotswapProjects/HotswapAgent#390]
Please excuse that this is more of a question than an issue.

I have a project that is still using Seam 2. From Google I found out, that Seam support was once listed, but now disappeared from the list of built-in plugins.

My questions are the following:

1. Can I still expect to have HotswapAgent  work out of the box with Seam 2?
2. If not, is there a way to reactivate support for this by adding a plugin (How can I do this)?

I am using Java 11 with dcevm-11.0.10+4.

Thanks for this great project to all involved.

**Comment by skybber** [comment]
Seam plugin was very simple, it cleared `messages` cache only. Definitively HA will be helpful for your development, I have used it for Seam project development before we have migrated it to CDI/Deltaspike

**Comment by stolp** [comment]
Thanks for replying, this fully answers my question!
