### ISSUE TITLE
Hot Swap takes a long time or even hangs with error

### ISSUE THREAD

**Issue by Matsuuu** [HotswapProjects/HotswapAgent#402]
Hey, I've noticed that there's a case in which the hotswap agent seems to take a long time and there's error related in the console:

```
09:26:37,594 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 09:26:37.594 ERROR (org.hotswap.agent.plugin.jdk.JdkPlugin) - flushClassInfoCache() exception Unable to make field private static final com.sun.beans.util.Cache com.sun.beans.introspect.ClassInfo.CACHE accessible: module java.desktop does not "opens com.sun.beans.introspect" to unnamed module @4567f35d.
```

This is being repeated multiple times in the wildfly console output.

Setup: 
Wildfly 24
IntelliJ Idea 2021.2.1

**Comment by skybber** [comment]
It should not hapen since TravaOpenJDK opens this module. Are you using TravaOpenJDK?

**Comment by Matsuuu** [comment]
I downloaded the " jdk11-dcevm with integrated HotswapAgent" https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases

I then pointed my wildfly setup to use that JDK

**Comment by Matsuuu** [comment]
Do I need to set IntelliJ Idea to use the same jdk too?

**Comment by skybber** [comment]
It is strange since TravaOpenJDK [opens](https://github.com/HotswapProjects/openjdk-jdk11u-dcevm/blob/dcevm11-jdk-11.0.12-adoptium/src/hotspot/share/runtime/arguments.cpp#L4377) the introspect module automatically. You  can try open module manually by `--add-opens java.desktop/com.sun.beans.introspect=ALL-UNNAMED`

**Comment by Matsuuu** [comment]
That seemed to fix it. After adding that to my wildfly configuration into the java opts, I've (at least with some short testing) not seen the error message anymore, thanks!
