### ISSUE TITLE
Support for JDK 17

### ISSUE THREAD

**Issue by achimmihca** [HotswapProjects/HotswapAgent#404]
[JDK 17](https://openjdk.java.net/projects/jdk/17/) has been released on 14 September 2021.
This is an LTS version such that HotswapAgent should support JDK 17.

There is a bundle of JDK11+HotswapAgent: https://github.com/TravaOpenJDK/trava-jdk-11-dcevm
Similarly, JDK17+HotswapAgent should be bundled.

**Comment by roeltje25** [comment]
I have this working using the jdk 17 from JetBrains (jbr_jcef-17-windows-x64-b135.1) and adding hotswapagent jar manually to lib/hotswap and running with the following options:
-XX:+AllowEnhancedClassRedefinition -javaagent:"D:\jbr_jcef-17-windows-x64-b135.1\lib\hotswap\hotswap-agent.jar"
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED --add-modules=java.se --add-exports=java.desktop/sun.awt=ALL-UNNAMED
 --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED
 --add-opens=java.base/java.lang=ALL-UNNAMED
 --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
 --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
 --add-opens=java.base/java.io=ALL-UNNAMED
 --add-opens=java.base/java.security=ALL-UNNAMED
 --add-opens=java.base/java.util=ALL-UNNAMED
 --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
 --add-opens=java.management/javax.management=ALL-UNNAMED
 --add-opens=java.naming/javax.naming=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED --add-modules=java.se --add-opens=java.desktop/com.sun.beans.introspect=ALL-UNNAMED --add-exports=java.desktop/com.sun.beans.util=ALL-UNNAMED 


however, it seems the JdkPlugin does not work as a private static field of the java.beans.Introspector class called declaredMethodCache is accessed, but it does not exist anymore.

**Comment by NicklasWallgren** [comment]
The `JdkPlugin` issue should hopefully be fixed as of https://github.com/HotswapProjects/HotswapAgent/pull/413/files
