### ISSUE TITLE
Add jackson plugin

### ISSUE THREAD

**Issue by liuzhengyang** [HotswapProjects/HotswapAgent#411]
Jackson is used by spring mvc to convert model result to json string.
Jackson saves some type cache in internal to improve performance.
For example, there is _rootDeserializers cache field in com.fasterxml.jackson.databind.ObjectMapper. These caches cause new field can not be read from json or be written to json.
#410

**Comment by skybber** [comment]
Great! Is it complete?

**Comment by liuzhengyang** [comment]
Yes, it is complete. I have tested in my project.
