### ISSUE TITLE
inteleji idea ultimate 2022.2.3 and Java 1.8.0_181 - hierarchy change not implemented : Operation not supported by VM

### ISSUE THREAD

**Issue by redkatok** [HotswapProjects/HotswapAgent#446]
I have a problem during local development with jdk1.8.0_181 and gradle multi module project build and deployed as single war on Tomcat 8.5.68 

When I try to change code at runtime of application  and use hotkey -  reload changed classes ->

I get next exception - **hierarchy change not implemented MyApp : Operation not supported by VM**

I checked what VM used - java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Dynamic Code Evolution 64-Bit Server VM (build 25.71-b01-dcevmlight-26, mixed mode)

In inteleji application configuratiuon I also specified next - -XXaltjvm=dcevm
-javaagent:C:\Users\developer\Desktop\hotswap-agent-1.4.2-SNAPSHOT.jar

I dont undestand what reason of this exception - please help

**Comment by jemmno** [comment]
Do you resolve this @redkatok  ?

**Comment by skybber** [comment]
Have you changed superclass? Since java7 Dcevm  does not support supperclass change (Hierarchy change).

**Comment by skybber** [comment]
Since Dcevm7 the super class switch is not supported.
