### ISSUE TITLE
DCEVM installation not found for JDK specified for the current project

### ISSUE THREAD

**Issue by fishBone000** [HotswapProjects/HotswapAgent#457]
Version numbers of IDE, HotswapAgent, JDK e.t.c. that I use / configured: 
- IntelliJ IDEA 2022.3
- HotSwapAgent 1.3.0, installed from IDEA Marketplace
- JBRSDK (DCEVM) 17.0.1 B164.4 win x64, as configured in Project Structures in my IDE, I also tried: 
- - JBR (fast-debug) 17.0.6 B829 win x64
- - JBRSDK (JCEF) 17.0.6 B829 win x64
- jbr-17 DCEVM as configured in Run/Debug configuration

What I encountered: 
- "DCEVM installation not found for JDK specified for the current project. You should download and install it. " in Settings -> Tools -> HotSwapAgent, and DCEVN version says "<not determined>". By the way, because I use hotswapping for Minecraft modding, so I must use Java 17 or later, so DCEVM for Java 8 or 11 is not possible for me. 

What I tried: 
- Adding "-XX:+AllowEnhancedClassRedefinition -XX:HotswapAgent=fatjar" to VM options of my Run/Debug configuration. 
- Copying hotswap-agent.jar (as shown in Agent Installation in HotswapAgent settings) to [JBRSDK (DCEVM) 17.0.1 B164.4 directory]/lib/hotswap
- Adding JBRSDK to my JAVA_HOME and PATH, while it's also configured as JDK in my IDE. 
- Set "Reload classes after compilation" to Always. 
- Set "Enable HotSwapAgent in all configurations" to enabled. 

Not sure what's going on, need help!

**Comment by skybber** [comment]
Please, don't use DCEVM intellij plugin, since it is for java8. Otherwise your setup looks correct, may be you can use latest snapshot HA release https://github.com/HotswapProjects/HotswapAgent/releases

**Comment by fishBone000** [comment]
Tried to use the jar from the release page provided by skybber, but still failed. I think it's related to my project, since it uses its own class loader. Didnt do any further test, will close this issue. 
By the way, thanks!
