### ISSUE TITLE
IntelliJ plugin or other easy way to launch from IntelliJ

### ISSUE THREAD

**Issue by Artur-** [HotswapProjects/HotswapAgent#492]
While HotSwapAgent is super great to use, there is one problem that you can see here in this issue tracker and also when talking to people about it: People find it too difficult to get started. Even if you have IntelliJ which already contains the needed JetBrains Runtime, it is still difficult. You need to 
1. figure out where the bundled jbr is, on Mac it is in a "dangerous" location inside /Application/...  or download the correct jbr among a hundred or so versions on a github page
2. download hotswapagent and place it in the correct folder, /Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/lib is not very obvious, especially as you then need to create a correctly named folder there
3. Ensure that you are actually using jbr when launching the application
4. Define custom VM arguments to your launch: `-XX:+AllowEnhancedClassRedefinition -XX:HotswapAgent=fatjar`

Now if you did everything correctly you might have hotswapagent up and running. If it does not work, it is really hard to say which step went wrong.

Could this be made trivial by creating a (quite small) IntelliJ plugin? The natural, and only needed, feature would be to have an additional option in the run dialog
<img width="344" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/260340/bb8a6b26-49cb-49cb-b93a-796722c7ea52">
that would say `Debug 'Application.main()' using HotSwapAgent`

Presumably a plugin could use the internal JetBrains Runtime, bundle the latest version of HotSwapAgent and then only ensure that launching happens with everything in the correct place. Either place the hotswapagent jar inside jbr or then, probably more safe, launch with hotswapagent outside jbr but using `-javaagent` or whatever options there might be. If the internal jbr poses problem, the plugin could even bundle jbr

Is this a good or bad idea? Are there other, better options to make it one-click?

**Comment by skybber** [comment]
Thanks for suggestion, I'll look at it. May be it could work in simillar way how the YourKit buttons is working now.

**Comment by Artur-** [comment]
Did you get a chance to look at this?

**Comment by gejun123456** [comment]
@Artur-  here is a intellij HotSwapHelper that can help you do that, just download the jdk no need to configure more it will work. Here is the doc:  https://github.com/gejun123456/HotSwapHelper 
The plugin site: https://plugins.jetbrains.com/plugin/25171-hotswaphelper

**Comment by Artur-** [comment]
Nice @gejun123456, we also ended up implementing something similar, albeit a bit more Vaadin specific, in the [Vaadin IntelliJ plugin](https://github.com/vaadin/intellij-plugin).

**Comment by gejun123456** [comment]
@Artur- I recently reviewed your project and noticed that some parts of the code are quite similar to my HotSwapHelper https://github.com/gejun123456/HotSwapHelper  I'm glad to see these similarities—does this mean you referenced my project during your development?

If you did use it as a reference, I would really appreciate it if you could mention my software as a reference in your project's README. If you have any questions or would like to discuss further, feel free to reach out to me.

**Comment by Artur-** [comment]
Added a mention here https://github.com/vaadin/intellij-plugin

I think we can close this issue now that there are two solutions to the problem: HotSwapHelper for everybody and the Vaadin plugin if you use Vaadin
