### ISSUE TITLE
Can HotswapAgent support add @Resource/@Autowired fields in springboot based project?

### ISSUE THREAD

**Issue by lijunjie1991** [HotswapProjects/HotswapAgent#495]
My project is springboot based

The code before modified like below:
```
@Service
public class FooServiceImpl implements FooService {

  @Resource private BarService barService;

  public void test() {
    log.info("just a test function");
  } 
  ......
}
```

The code after modified like below:
```
@Service
public class FooServiceImpl implements FooService {

  @Resource private BarService barService;
  // added a field
  @Resource private TestService testService;

  public void test() {
    log.info("just a test function: {}", testService);
  } 
  ......
}
```

After reload this class, and run test method, then i got the result:
```
just a test function: null
```

**Comment by zzhlhc** [comment]
@skybber it seems to be a dcevm issue because in IntelliJ IDEA, it shows "schema change not implemented .... Operation not supported by VM".
I'm wondering if this is impossible to achieve or just requires someone to do it.

**Comment by skybber** [comment]
Probably you don't use dcevm or did not turn it on using `-XX:-AllowEnhancedClassRedefinition`

**Comment by zzhlhc** [comment]
I checked what you said(add -XX:-AllowEnhancedClassRedefinition), but nothing changes.
If i only change method body, hot swap succeeds after rebuilding the Java file, doesn't this indicate that i'm using dcevm?
BTW, i'm using jdk8 and [HotSwapAgent plugin](https://plugins.jetbrains.com/plugin/9552-hotswapagent).

Whatever, you mean that dcevm theoretically supports adding fields, right?

**Comment by lijunjie1991** [comment]
> I checked what you said(add -XX:-AllowEnhancedClassRedefinition), but nothing changes. If i only change method body, hot swap succeeds after rebuilding the Java file, doesn't this indicate that i'm using dcevm? BTW, i'm using jdk8 and [HotSwapAgent plugin](https://plugins.jetbrains.com/plugin/9552-hotswapagent).
> 
> Whatever, you mean that dcevm theoretically supports adding fields, right?

@zzhlhc I got the same error as you, and i am using jdk8 too...
```
schema change not implemented .... Operation not supported by VM
```

**Comment by skybber** [comment]
It's an old plugin, could you check the settings by http://hotswapagent.org/mydoc_quickstart.html ?

**Comment by zzhlhc** [comment]
> It's an old plugin, could you check the settings by http://hotswapagent.org/mydoc_quickstart.html ?

Thanks!

It's indeed plugin's problem, i uninstalled the plugin and completed `quickstart` (skipped `IDE specific setup guides`) ,  then it worked well.

I think there might be more IntelliJ IDEA users are misled by this plugin...

@lijunjie1991  you can try.

**Comment by jdideepak** [comment]
@skybber @zzhlhc I am also trying to set up Hotswap Agent. Will Hotswap Agent work if I have a running WAR in Tomcat and then attach a debugger using Hotswap Agent?

**Comment by skybber** [comment]
> [@skybber](https://github.com/skybber) [@zzhlhc](https://github.com/zzhlhc) I am also trying to set up Hotswap Agent. Will Hotswap Agent work if I have a running WAR in Tomcat and then attach a debugger using Hotswap Agent?

It should work in this way.

**Comment by jdideepak** [comment]
<img width="924" height="634" alt="Image" src="https://github.com/user-attachments/assets/92e30ed1-bcd8-44a8-af72-08934cea27e5" />

It is not able to detect my jdk version.

And also when I add the DCEVM flag in my catalina file it is not starting up. I am adding this flag `-XXaltjvm=dcevm` 

<img width="493" height="203" alt="Image" src="https://github.com/user-attachments/assets/3b12fe6b-e598-4f28-9e5a-4b1ae279b78b" />

**Comment by jdideepak** [comment]
@skybber Both the jdk and DCEVM version should match to make this work. After visiting so many vendors website for jdk I found 8u171 from azul and now everyting is working (I want to have different vendor than oracle).
Can I contribute to the guide? I think we should add this note there.

Thank you, awesome project :)

**Comment by skybber** [comment]
> [@skybber](https://github.com/skybber) Both the jdk and DCEVM version should match to make this work. After visiting so many vendors website for jdk I found 8u171 from azul and now everyting is working (I want to have different vendor than oracle). Can I contribute to the guide? I think we should add this note there.
> 
> Thank you, awesome project :)

You can add note about it to README.md.

**Comment by jdideepak** [comment]
@skybber 
Raised a PR: https://github.com/HotswapProjects/HotswapAgentPages/pull/23
Please take a look.
