### ISSUE TITLE
Linkage error in Wildfly because of differences between JasperLoader and ModuleClassLoader.

### ISSUE THREAD

**Issue by negora** [HotswapProjects/HotswapAgent#50]
I don't know how class loaders work. I only have a vague idea. So I'm sorry if I'm not precise with this description. Here I go...

I'm running Wildfly 8.1.0, with JDK 8 Update 05 and HotswapAgent 0.1 Beta 4. I've successfully installed DCEVM 25.5-b02-dcevmlight-58 as an alternative JVM. I've been able to correctly hotswap several classes. However, I've problems when the class that I hotswap is used in a JSP file but has been instantiated from a class stored in WEB-INF/classes/ . Every time that I do that, I got a java.lang.LinkageError.

Testing it is very easy. Create a WAR file with a class that instantiates itself. For example:

  package myweb;

  public class Test {

```
private Test () {
}

public static Test create () {
  return new Test ();
}
```

  }

Then write a call to myweb.Test.create () in a JSP file and request such JSP from your browser. It's OK. Now edit the class as you want, submit the changes with your IDE and request the JSP again. It will fail and the server will output:

java.lang.LinkageError: loader constraint violation: when resolving method "myweb.Test.create()Lmyapp/Test;" the class loader (instance of org/apache/jasper/servlet/JasperLoader) of the current class, org/apache/jsp/test_jsp, and the class loader (instance of org/jboss/modules/ModuleClassLoader) for the method's defining class, myapp/Test, have different Class objects for the type myapp/Test used in the signature

It seems that both class loaders, JasperLoader and ModuleClassLoader, keep a different version of the same class. One of them isn't updated properly.

Thank you.

**Comment by edudant** [comment]
Please reopen if still valid.
