### ISSUE TITLE
Can not get a JavaCompiler instance with jbr_17.0.7

### ISSUE THREAD

**Issue by spilledyear** [HotswapProjects/HotswapAgent#505]
# ENV
1. hotSwapAgent version: 1.4.2-SNAPSHOT
2. JDK: [jbrsdk-17.0.9-linux-x64-b1087.3.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.3.tar.gz)
3. start with： 
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
-XX:+AllowEnhancedClassRedefinition
-XX:XX:HotswapAgent=external
-javaagent:/Users/admin/Downloads/hotswap-agent.jar

# question
can not get a JavaCompiler instance with DynamicCompileToolProvider#JavaCompiler.
```java
    private static final String defaultJavaCompilerName = "com.sun.tools.javac.api.JavacTool";

    /**
     * Gets the Java&trade; programming language compiler provided
     * with this platform.
     * @return the compiler provided with this platform or
     * {@code null} if no compiler is provided
     */
    public static JavaCompiler getSystemJavaCompiler() {
        return instance().getSystemTool(JavaCompiler.class, defaultJavaCompilerName);
    }
```

i see the code in javax.tools.ToolProvider  look like
![aa025b19-6818-4ebe-bafe-bfb30981d59f](https://github.com/HotswapProjects/HotswapAgent/assets/24663965/d0ed7b66-dc75-4042-8291-492f7d779aaa)

**Couldn't be decomplied** . so can you tell me how to get a JavaCompiler instance in JBR_17.0.7

**Comment by skybber** [comment]
It seems that it is not HA issue but JBR issue, I suggest to ask the question on JBR YT : https://youtrack.jetbrains.com/issues/JBR
