### ISSUE TITLE
Executing ReloadJavaProxyCommand caused an infinite loop

### ISSUE THREAD

**Issue by spilledyear** [HotswapProjects/HotswapAgent#506]
# Env
1. JDK: JBR_17.0.7
2. hotswapAgent 1.4.2

# Question
1. there is a Mybatis Mapper interface
```
public interface IcarusTaskFile400Mapper{
    List<IcarusTaskFile> selectList();
}
```

2. try to add a methd in this interface, look like
```
public interface IcarusTaskFile400Mapper{
    List<IcarusTaskFile> selectList();

    @Select("select * from icarus_task_file WHERE service_name = 'icarus-admin' LIMIT 2 ")
    List<IcarusTaskFile> selectList22();
```
3. reload interface in IDEA
4. caused an infinite loop
![image](https://github.com/HotswapProjects/HotswapAgent/assets/24663965/69258e75-4225-4727-95ab-26f54c266764)

ProxyClassSignatureHelper.getJavaClassSignature(clazz)  return a clazzSignature without annotation info

**Comment by RaymondLam1** [comment]
The same question.

**Comment by RaymondLam1** [comment]
I'm using idea and I found that this phenomenon is triggered when starting in debug mode

**Comment by skybber** [comment]
Probably related to issue https://github.com/HotswapProjects/HotswapAgent/issues/429 , and commit https://github.com/HotswapProjects/HotswapAgent/commit/15efa269ae7d37ae43d17381630b3fb620c85bae

**Comment by RaymondLam1** [comment]
It seems to be a bug casued by `ProxyPlugin.removeProxyDefiningClassName(className);`  in org.hotswap.agent.plugin.proxy.ReloadJavaProxyCommand#executeSingleCommand.

It performs repeated remove operations on proxyRedefiningMap, and cause an infinite loop.

**Comment by RaymondLam1** [comment]
This problem doesn't only exist in debug mode. In my project, it behaves "normally" in a weird way in run mode.
