### ISSUE TITLE
An error occurred during hot update of application.properties configuration file

### ISSUE THREAD

**Issue by XuxuGood** [HotswapProjects/HotswapAgent#535]
![1709027360927](https://github.com/HotswapProjects/HotswapAgent/assets/45960164/07a7067a-09c4-4444-9f9d-313101668e6d)

**Comment by skybber** [comment]
Could you specify what HA version are you using?

**Comment by XuxuGood** [comment]
> Could you specify what HA version are you using?

This problem has been solved, but a new problem has arisen. Updating the application.properties file does not take effect.

This is my new output log code：

<img width="1001" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/2b5d0c12-832a-4409-aca6-e1a3ed4826c9">

This is the configuration content before the change:

<img width="369" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/85fb2ccf-814a-41e9-9627-f54f1e02861f">

This is the changed file content:

<img width="435" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/e9aad316-8ae0-4ab1-a029-53d4bcc85163">

This is the output log of the service, there is no change in the old and new values:

<img width="809" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/a0969f98-1bb3-4f00-89a9-7028846908e0">

other instructions：

Service startup: Use `java -XXaltjvm=dcevm -javaagent:hotswapagent.jar -cp . mainclass` to start the service.

Actually observe that the contents of the application.properties file are indeed updated to the BOOT-INF directory.

<img width="935" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/764ba45b-6b7b-46a6-be2f-599a3fe0050b">

Environment version information:
hotswapagent：1.4.2-SNAPSHOT
java：1.8

**Comment by XuxuGood** [comment]
> Could you specify what HA version are you using?

Is there a problem here? The new configuration file attributes are not flushed into the memory.

<img width="952" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/4d78b25d-c40f-4a0a-b0aa-3d56e422c8fb">
