### ISSUE TITLE
Why does the hotswapagent 1.4.2-SNAPSHOT version of the jar not contain the springboot plug-in?

### ISSUE THREAD

**Issue by XuxuGood** [HotswapProjects/HotswapAgent#536]
<img width="1051" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/d7f3c4b5-f533-487e-8250-66916be2a82c">

**Comment by XuxuGood** [comment]
Need to introduce dependencies, master branch code

<img width="1438" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/1134546f-978a-4fab-b6c5-71777213e68a">

**Comment by DustinQiao** [comment]
Could you please share the latest jar contains spring boot plugin?

**Comment by XuxuGood** [comment]
> Could you please share the latest jar contains spring boot plugin?

The markdown page does not seem to support the jar file above. How can I share it?

**Comment by DustinQiao** [comment]
> > Could you please share the latest jar contains spring boot plugin?
> 
> The markdown page does not seem to support the jar file above. How can I share it?

[hotswap-agent-1.4.2-SNAPSHOT.jar.zip](https://github.com/HotswapProjects/HotswapAgent/files/14455776/hotswap-agent-1.4.2-SNAPSHOT.jar.zip)

I built a new jar with SpringBoot, only support java1.8, please try
It works good on my project, hotswap .properties file perfectly

**Comment by skybber** [comment]
Fixed + snapshot updated. Thanks for report!
