### ISSUE TITLE
java -jar update mybatis failure

### ISSUE THREAD

**Issue by XuxuGood** [HotswapProjects/HotswapAgent#542]
java -XXaltjvm=dcevm -javaagent:/www/app-preview/hotswap-agent-1.4.2-SNAPSHOT.jar=autoHotswap=true,propertiesFilePath=/www/app-preview/hotswap-agent.properties -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8005 -jar /www/app-preview/app/app-preview-push-1.0.0-SNAPSHOT.jar

<img width="510" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/586b70c3-2627-45b3-98b1-f5daac397e81">

cause by:

<img width="1177" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/a19aa8be-2058-47b5-b45a-fa0ef6b5814e">

<img width="881" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/b915ba3f-24a8-4295-8b63-755347a8c08e">

<img width="823" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/08cd9c3e-412f-4df6-a61f-72aa7d0c3847">

<img width="786" alt="image" src="https://github.com/HotswapProjects/HotswapAgent/assets/45960164/30f24d66-a3a5-4fd6-9435-6f25354776f5">

**Comment by skybber** [comment]
What version of dcevm/jbr are you using? Could you supply minimal reproducer?

**Comment by XuxuGood** [comment]
> What version of dcevm/jbr are you using? Could you supply minimal reproducer?

dcevm version: 1.8_181

This is my mybatis sample project:
[app-preview-push.zip](https://github.com/HotswapProjects/HotswapAgent/files/14631854/app-preview-push.zip)
