### ISSUE TITLE
Release 1.4.2

### ISSUE THREAD

**Issue by Artur-** [HotswapProjects/HotswapAgent#561]
Do you have any plans on releasing a new stable version? The automatic snapshot version is great for testing for not so great for real world usage

**Comment by skybber** [comment]
I've had this task pending for a while, but it depends on the availability of J. Bubnik, who has the necessary rights to perform the Maven release. I'll make an effort to push this forward, especially since many plugins, particularly those related to Jakarta, are now production-ready.

**Comment by skybber** [comment]
We have released HA 2.0.0 today, it is available on maven!
