### ISSUE TITLE
Use retransformClasses to replace redefineClasses to avoid bytecode update failure.

### ISSUE THREAD

**Issue by hengyunabc** [HotswapProjects/HotswapAgent#564]
Currently, the hotswap agent uses redefineClasses to update bytecode. However, when another Java agent triggers retransformClasses, redefineClasses will become ineffective. Therefore, it is necessary to use retransformClasses instead of redefineClasses to avoid this issue.

https://github.com/HotswapProjects/HotswapAgent/blob/RELEASE-1.4.1/hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginManager.java#L292

What are the specific reasons for not using retransformClasses and instead using redefineClasses?

**Comment by skybber** [comment]
We could change it, there is no specific reason for it as I know.

**Comment by skybber** [comment]
I've examined it in more detail. We must provide a new bytecode for that class in this place. The redefineClasses method allows the classes along with their corresponding new bytecode as arguments. In contrast, retransformClasses only accepts classes without the ability to supply new bytecode. Therefore, we can't change it to retransformClasses.

**Comment by hengyunabc** [comment]
> I've examined it in more detail. We must provide a new bytecode for that class in this place. The redefineClasses method allows the classes along with their corresponding new bytecode as arguments. In contrast, retransformClasses only accepts classes without the ability to supply new bytecode. Therefore, we can't change it to retransformClasses.

In above pr, retransformClasses works.
