### ISSUE TITLE
Default logging is very verbose

### ISSUE THREAD

**Issue by michielproce** [HotswapProjects/HotswapAgent#57]
If you're experienced with DCEVM, HotswapAgent is easy to get running.
My only problem with the default is that the logging is a very verbose. I'm having trouble following my own application's logging.

Most of the logging looks like this:
```
(-1 / -1) (org/hotswap/agent/plugin/jvm/AnonymousClassInfos$AnonymousClassInfoMatcher/org/hotswap/agent/plugin/jvm/AnonymousClassInfos$AnonymousClassInfoMatcher)
{instance class} 
 - klass: {other class}
{instance class} 
 - klass: {other class}
```

I've tried disabling the logging but it appears my `LOGGER=warn` in a hotswap-agent.properties in my classpath doesn't seem to be picked up.

(BTW: Thanks for a pretty great alternative to JRebel :))

**Comment by michielproce** [comment]
I'm using JDK 1.7.0_51 64 bit (host: Win7), DCEVM 24.51-b03-dcvmfull-3 (latest on dcevm.github.io).
I'm running an webapplication on Tomcat 7.0.50.

I've noticed that the verbose logging does not happen at other webapps, so there might be something application specific going on. If I run the application with DCEVM but without HotswapAgent the logging stops.
How can I suppress  these messages? 

If you need additional information, let me know.

**Comment by skybber** [comment]
Logging Source of this stuff is definitively DCEVM or OpenJDK respectively. I did some private patch, because I hate this mess.

**Comment by vpablos** [comment]
Do you have the patch somewhere?
Could you tell us how to patch?
Thanks in advance.

**Comment by skybber** [comment]
do the following is for 7u85 (or find out the lines in other versions):

diff --git a/src/share/vm/classfile/systemDictionary.cpp b/src/share/vm/classfile/systemDictionary.cpp
index 39ec219..1321603 100644
--- a/src/share/vm/classfile/systemDictionary.cpp
+++ b/src/share/vm/classfile/systemDictionary.cpp
@@ -2032,7 +2032,7 @@ void SystemDictionary::check_constraints(int d_index, unsigned int d_hash,
       assert(check->klass_part()->oop_is_instance(), "noninstance in systemdictionary");
       if ((defining == true) && ((k() != check) && k->old_version() != check)) {
         ResourceMark rm(Thread::current());
-        tty->print_cr("(%d / %d) (%s/%s)", k->revision_number(), check->klass_part()->revision_number(), k->name()->as_C_string(), check->klass_part()->name()->as_C_string());
+        // tty->print_cr("(%d / %d) (%s/%s)", k->revision_number(), check->klass_part()->revision_number(), k->name()->as_C_string(), check->klass_part()->name()->as_C_string());
         k()->print();
         check->print();
         linkage_error = "loader (instance of  %s): attempted  duplicate class "
diff --git a/src/share/vm/oops/klass.cpp b/src/share/vm/oops/klass.cpp
index 19a9f5b..8361662 100644
--- a/src/share/vm/oops/klass.cpp
+++ b/src/share/vm/oops/klass.cpp
@@ -601,7 +601,7 @@ jint Klass::jvmti_class_status() const {
 void Klass::oop_print_on(oop obj, outputStream* st) {
   ResourceMark rm;
   // print title
-  st->print_cr("%s ", internal_name());
+  // st->print_cr("%s ", internal_name());
   obj->print_address_on(st);
 
   if (WizardMode) {
@@ -610,15 +610,15 @@ void Klass::oop_print_on(oop obj, outputStream* st) {
   }
 
   // print class
-  st->print(" - klass: ");
+  // st->print(" - klass: ");
   obj->klass()->print_value_on(st);
-  st->cr();
+  //st->cr();
 }
 
 void Klass::oop_print_value_on(oop obj, outputStream* st) {
   // print title
   ResourceMark rm;              // Cannot print in debug mode without this
-  st->print("%s", internal_name());
+  // st->print("%s", internal_name());
   obj->print_address_on(st);
 }

**Comment by skybber** [comment]
I've commented following lines:

'''
diff --git a/src/share/vm/classfile/systemDictionary.cpp b/src/share/vm/classfile/systemDictionary.cpp
index 39ec219..1321603 100644
--- a/src/share/vm/classfile/systemDictionary.cpp
+++ b/src/share/vm/classfile/systemDictionary.cpp
@@ -2032,7 +2032,7 @@ void SystemDictionary::check_constraints(int d_index, unsigned int d_hash,
       assert(check->klass_part()->oop_is_instance(), "noninstance in systemdictionary");
       if ((defining == true) && ((k() != check) && k->old_version() != check)) {
         ResourceMark rm(Thread::current());
-        tty->print_cr("(%d / %d) (%s/%s)", k->revision_number(), check->klass_part()->revision_number(), k->name()->as_C_string(), check->klass_part()->name()->as_C_string());
+        // tty->print_cr("(%d / %d) (%s/%s)", k->revision_number(), check->klass_part()->revision_number(), k->name()->as_C_string(), check->klass_part()->name()->as_C_string());
         k()->print();
         check->print();
         linkage_error = "loader (instance of  %s): attempted  duplicate class "
diff --git a/src/share/vm/oops/klass.cpp b/src/share/vm/oops/klass.cpp
index 19a9f5b..8361662 100644
--- a/src/share/vm/oops/klass.cpp
+++ b/src/share/vm/oops/klass.cpp
@@ -601,7 +601,7 @@ jint Klass::jvmti_class_status() const {
 void Klass::oop_print_on(oop obj, outputStream* st) {
   ResourceMark rm;
   // print title
-  st->print_cr("%s ", internal_name());
+  // st->print_cr("%s ", internal_name());
   obj->print_address_on(st);
 
   if (WizardMode) {
@@ -610,15 +610,15 @@ void Klass::oop_print_on(oop obj, outputStream* st) {
   }
 
   // print class
-  st->print(" - klass: ");
+  // st->print(" - klass: ");
   obj->klass()->print_value_on(st);
-  st->cr();
+  //st->cr();
 }
 
 void Klass::oop_print_value_on(oop obj, outputStream* st) {
   // print title
   ResourceMark rm;              // Cannot print in debug mode without this
-  st->print("%s", internal_name());
+  // st->print("%s", internal_name());
   obj->print_address_on(st);
 }
 '''

**Comment by skybber** [comment]
Comment following lines (this is for v7u85):

```
diff --git a/src/share/vm/classfile/systemDictionary.cpp b/src/share/vm/classfile/systemDictionary.cpp
index 39ec219..1321603 100644
--- a/src/share/vm/classfile/systemDictionary.cpp
+++ b/src/share/vm/classfile/systemDictionary.cpp
@@ -2032,7 +2032,7 @@ void SystemDictionary::check_constraints(int d_index, unsigned int d_hash,
       assert(check->klass_part()->oop_is_instance(), "noninstance in systemdictionary");
       if ((defining == true) && ((k() != check) && k->old_version() != check)) {
         ResourceMark rm(Thread::current());
-        tty->print_cr("(%d / %d) (%s/%s)", k->revision_number(), check->klass_part()->revision_number(), k->name()->as_C_string(), check->klass_part()->name()->as_C_string());
+        // tty->print_cr("(%d / %d) (%s/%s)", k->revision_number(), check->klass_part()->revision_number(), k->name()->as_C_string(), check->klass_part()->name()->as_C_string());
         k()->print();
         check->print();
         linkage_error = "loader (instance of  %s): attempted  duplicate class "
diff --git a/src/share/vm/oops/klass.cpp b/src/share/vm/oops/klass.cpp
index 19a9f5b..8361662 100644
--- a/src/share/vm/oops/klass.cpp
+++ b/src/share/vm/oops/klass.cpp
@@ -601,7 +601,7 @@ jint Klass::jvmti_class_status() const {
 void Klass::oop_print_on(oop obj, outputStream* st) {
   ResourceMark rm;
   // print title
-  st->print_cr("%s ", internal_name());
+  // st->print_cr("%s ", internal_name());
   obj->print_address_on(st);
 
   if (WizardMode) {
@@ -610,15 +610,15 @@ void Klass::oop_print_on(oop obj, outputStream* st) {
   }
 
   // print class
-  st->print(" - klass: ");
+  // st->print(" - klass: ");
   obj->klass()->print_value_on(st);
-  st->cr();
+  //st->cr();
 }
 
 void Klass::oop_print_value_on(oop obj, outputStream* st) {
   // print title
   ResourceMark rm;              // Cannot print in debug mode without this
-  st->print("%s", internal_name());
+  // st->print("%s", internal_name());
   obj->print_address_on(st);
 }
```

**Comment by vpablos** [comment]
Thank you very much. It works perfectly for 7u79 too.

I've asked DCEVM developers to apply your patch or something similar when in production mode
https://github.com/dcevm/dcevm/issues/86

Hope it helps other people.

**Comment by skybber** [comment]
My solution is hack. I didn't study the purpose, why the messages are printed directly to stdout. There should be another solution how to avoid this.

**Comment by PrabakaranSK** [comment]
@skybber  - Would you be kind enough to patch the DCE VM source all by yourself, as it seems no one is assigned to fix this issue on DCEVM side?

**Comment by cchilds** [comment]
I have spent days trying to get dcevm to compile with no success. If someone here has or could get a build of java 7u79 full, with these logging fixes applied, I would love you forever.

**Comment by skybber** [comment]
Since I'm Linux user I have no problems with it. I've tried win32 build under wine and failed too since current wine version (wine-stagged too) has problems with cygwin. Some step-by-step manual howto build dcevm for win32 would be appreciated a lot!

**Comment by vpablos** [comment]
cchilds, if you use debian/ubuntu you can use the following url as repository:
http://babel.ls.fi.upm.es/~vpablos/others/packages/debian/

If not, you can always download the package and extract the files from it.
By the way, eclipse Mars does not work with DCEVM.

**Comment by cchilds** [comment]
Thanks @vpablos, but unfortunately, I'm using Windows. Thanks anyway.

What issues are you having with Mars and DCEVM? I have used it with Mars quite a bit with no problems.
