### ISSUE TITLE
IDEA plugin: Enable reloading of only a selected subset of changed files

### ISSUE THREAD

**Issue by homejim** [HotswapProjects/HotswapAgent#573]
HA is a very useful tool, and I want to develop an HA IDEA plugin for my team with the following goals:

1. Automatically integrate dcevm's JDK.
2. Enable reloading of only a selected subset of changed files.
3. Support both remote and local usage.

Based on the second and third requirements, my approach is:

1. Modify HA to start a Java RMI or another TCP listener when the Agent starts.
2. The IDEA plugin will monitor file changes, list the changed files, and allow users to select which ones to reload.

Given this setup, my questions are:

1. For class files, after my RMI receives the class files, should I load the classes and use org.hotswap.agent.config.PluginManager#hotswap to perform the reload?
2. For non-class files such as XML, how should I handle them? Would using watchResources be a solution?

**Comment by homejim** [comment]
@skybber Do you have any good suggestions?

**Comment by skybber** [comment]
Great idea! There is already an obsolete HA plugin https://github.com/dmitry-zhuravlev/hotswap-agent-intellij-plugin. 

> HA is a very useful tool, and I want to develop an HA IDEA plugin for my team with the following goals:
> 
>     1. Automatically integrate dcevm's JDK.
> 
>     2. Enable reloading of only a selected subset of changed files.

It could be hard for unexperienced user. Selected subset must be linkable in dcevm, redefinition could fail in this case. I would recommend it as advanced/optional feature, in my worrk flow I would not probably use it at all.

> 
>     3. Support both remote and local usage.

What dou you mean local/remote ? Autohotswap / debugger ?

> 
> 
> Based on the second and third requirements, my approach is:
> 
>     1. Modify HA to start a Java RMI or another TCP listener when the Agent starts.
> 
>     2. The IDEA plugin will monitor file changes, list the changed files, and allow users to select which ones to reload.
> 
> 
> Given this setup, my questions are:
> 
>     1. For class files, after my RMI receives the class files, should I load the classes and use org.hotswap.agent.config.PluginManager#hotswap to perform the reload?
> 

In most common case the reload is done via debugger/jdi interface and HA use Instrumentation interface to modify and redefine class (processed by PluginManager). Another way of hotswap launching is from HotswapAgent `autoHotswap=true` and `extraClasspath=...` . For remote debugging a standard remote jdwp can be used: ` -agentlib:jdwp=transport=dt_socket,server=y,address=8000` Is there another reason for a new remote interface? 

>     2. For non-class files such as XML, how should I handle them? Would using watchResources be a solution?

Yes watch resources.

It would be great if the most commonly used HA options (such as autoHotswap, extraClasspath, watchResources, logging setup, and DCEVM logging `-Xlog:redefine+class*=info`) could be configured directly within the IntelliJ IDEA settings dialog. Additionally, I recommend using HA in external mode `-XX:HotswapAgent=external`. Otherwise, HA needs to be copied to the hosted JBR, which is also doable.

Otherwise, I'm very interested in the project! I have some experience with IDEA plugin development, and I'd be happy to help out if I have some free time.

**Comment by gejun123456** [comment]
hi i have made a intellij plugin  https://github.com/gejun123456/HotSwapHelper, it can add vm parameters when user click the run with hotswap button just like jrebel intellij plugin.  no need to set vm parameter by yourself. maybe you can start the plugin with the code.

**Comment by skybber** [comment]
> hi i have made a intellij plugin https://github.com/gejun123456/HotSwapHelper, it can add vm parameters when user click the run with hotswap button just like jrebel intellij plugin. no need to set vm parameter by yourself. maybe you can start the plugin with the code.

Cool!!!

**Comment by homejim** [comment]
> Great idea! There is already an obsolete HA plugin https://github.com/dmitry-zhuravlev/hotswap-agent-intellij-plugin.
> 
> > HA is a very useful tool, and I want to develop an HA IDEA plugin for my team with the following goals:
> > ```
> > 1. Automatically integrate dcevm's JDK.
> > 
> > 2. Enable reloading of only a selected subset of changed files.
> > ```
> 
> It could be hard for unexperienced user. Selected subset must be linkable in dcevm, redefinition could fail in this case. I would recommend it as advanced/optional feature, in my worrk flow I would not probably use it at all.
> 
> > ```
> > 3. Support both remote and local usage.
> > ```
> 
> What dou you mean local/remote ? Autohotswap / debugger ?
> 
> > Based on the second and third requirements, my approach is:
> > ```
> > 1. Modify HA to start a Java RMI or another TCP listener when the Agent starts.
> > 
> > 2. The IDEA plugin will monitor file changes, list the changed files, and allow users to select which ones to reload.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Given this setup, my questions are:
> > ```
> > 1. For class files, after my RMI receives the class files, should I load the classes and use org.hotswap.agent.config.PluginManager#hotswap to perform the reload?
> > ```
> 
> In most common case the reload is done via debugger/jdi interface and HA use Instrumentation interface to modify and redefine class (processed by PluginManager). Another way of hotswap launching is from HotswapAgent `autoHotswap=true` and `extraClasspath=...` . For remote debugging a standard remote jdwp can be used: ` -agentlib:jdwp=transport=dt_socket,server=y,address=8000` Is there another reason for a new remote interface?
> 
> > ```
> > 2. For non-class files such as XML, how should I handle them? Would using watchResources be a solution?
> > ```
> 
> Yes watch resources.
> 
> It would be great if the most commonly used HA options (such as autoHotswap, extraClasspath, watchResources, logging setup, and DCEVM logging `-Xlog:redefine+class*=info`) could be configured directly within the IntelliJ IDEA settings dialog. Additionally, I recommend using HA in external mode `-XX:HotswapAgent=external`. Otherwise, HA needs to be copied to the hosted JBR, which is also doable.
> 
> Otherwise, I'm very interested in the project! I have some experience with IDEA plugin development, and I'd be happy to help out if I have some free time.



> Great idea! There is already an obsolete HA plugin https://github.com/dmitry-zhuravlev/hotswap-agent-intellij-plugin.
> 
> > HA is a very useful tool, and I want to develop an HA IDEA plugin for my team with the following goals:
> > ```
> > 1. Automatically integrate dcevm's JDK.
> > 
> > 2. Enable reloading of only a selected subset of changed files.
> > ```
> 
> It could be hard for unexperienced user. Selected subset must be linkable in dcevm, redefinition could fail in this case. I would recommend it as advanced/optional feature, in my worrk flow I would not probably use it at all.
> 
> > ```
> > 3. Support both remote and local usage.
> > ```
> 
> What dou you mean local/remote ? Autohotswap / debugger ?
> 
> > Based on the second and third requirements, my approach is:
> > ```
> > 1. Modify HA to start a Java RMI or another TCP listener when the Agent starts.
> > 
> > 2. The IDEA plugin will monitor file changes, list the changed files, and allow users to select which ones to reload.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Given this setup, my questions are:
> > ```
> > 1. For class files, after my RMI receives the class files, should I load the classes and use org.hotswap.agent.config.PluginManager#hotswap to perform the reload?
> > ```
> 
> In most common case the reload is done via debugger/jdi interface and HA use Instrumentation interface to modify and redefine class (processed by PluginManager). Another way of hotswap launching is from HotswapAgent `autoHotswap=true` and `extraClasspath=...` . For remote debugging a standard remote jdwp can be used: ` -agentlib:jdwp=transport=dt_socket,server=y,address=8000` Is there another reason for a new remote interface?
> 
> > ```
> > 2. For non-class files such as XML, how should I handle them? Would using watchResources be a solution?
> > ```
> 
> Yes watch resources.
> 
> It would be great if the most commonly used HA options (such as autoHotswap, extraClasspath, watchResources, logging setup, and DCEVM logging `-Xlog:redefine+class*=info`) could be configured directly within the IntelliJ IDEA settings dialog. Additionally, I recommend using HA in external mode `-XX:HotswapAgent=external`. Otherwise, HA needs to be copied to the hosted JBR, which is also doable.
> 
> Otherwise, I'm very interested in the project! I have some experience with IDEA plugin development, and I'd be happy to help out if I have some free time.

Thanks。
Local and remote refer to the local development environment and the remote server. The goal of the plugin is to be able to push files from IntelliJ IDEA, after compilation, into a local or remote server's Java application, achieving code hotswap. What I want is a unified model. For the user, operating locally versus remotely is the same, except for the IP address, with the local default being localhost.

Why support reloading specific files? My initial thought was that sometimes users modify multiple files, but they may only want to push one or two of them to the application rather than all of them.

Of course, the plugin also supports options like automatically compiling and reloading upon changes.

Why not use JDWP? Firstly, users might not always start their applications in debug mode, especially on remote servers. Secondly, when it comes to remote scenarios, I'm unsure if JDWP allows for more precise control. I'll do some research to see if it can meet my requirements.

**Comment by homejim** [comment]
![image](https://github.com/user-attachments/assets/d02bfd2c-21c3-442a-b4cb-8d908a57d295)

Hotswapping only part of the files, somewhat similar to what this diagram illustrates.

**Comment by homejim** [comment]
https://pic.rmb.bdstatic.com/bjh/240317/bf10d142fa020481ef60adf0641310d58214.gif

Hotswapping only part of the files, somewhat similar to what this diagram illustrates.

**Comment by skybber** [comment]
> Thanks。 Local and remote refer to the local development environment and the remote server. The goal of the plugin is to be able to push files from IntelliJ IDEA, after compilation, into a local or remote server's Java application, achieving code hotswap. What I want is a unified model. For the user, operating locally versus remotely is the same, except for the IP address, with the local default being localhost.
> 
> Why support reloading specific files? My initial thought was that sometimes users modify multiple files, but they may only want to push one or two of them to the application rather than all of them.
> 
> Of course, the plugin also supports options like automatically compiling and reloading upon changes.
> 
> Why not use JDWP? Firstly, users might not always start their applications in debug mode, especially on remote servers. Secondly, when it comes to remote scenarios, I'm unsure if JDWP allows for more precise control. I'll do some research to see if it can meet my requirements.

As I understand your idea, you would use HA in `autoHotswap=true` mode. I think there could be two potential issues:

- How can you attach a remote debugger session without an open JDWP port? Perhaps HA could function as a JDWP agent?
- How do you correctly synchronize the state of the IntelliJ IDEA debugger with the JVM? I think this is a common problem with `autoHotswap=true`. At least, I encountered this issue in the past when using Eclipse.

**Comment by skybber** [comment]
> https://pic.rmb.bdstatic.com/bjh/240317/bf10d142fa020481ef60adf0641310d58214.gif
> 
> Hotswapping selected files, allowing the user to choose one or multiple files, somewhat similar to what this diagram illustrates.

It looks nice! In my workflow, I change the code and deploy all changes to the JVM without subset selecting, so this step is redundant for me.  However, it could be helpful for others.
