### ISSUE TITLE
could i add the intellij HotSwapHelper plugin to readme IDE support part?

### ISSUE THREAD

**Issue by gejun123456** [HotswapProjects/HotswapAgent#576]
The plugin is based on hotSwapAgent. make user easy to use with the framework. the plugin will automatical add vm parameters for user.  The repository is: https://github.com/gejun123456/HotSwapHelper

Screenshot:
![启动HotSwapHelper2](https://github.com/user-attachments/assets/46635d0e-92d3-4f23-a016-0a72157d0eb9)
![HotSwapHelperChangeCodeWork](https://github.com/user-attachments/assets/4b0b5b77-7ad9-4c89-8bbe-68fe0dcf72ef)

The plugin is available at: https://plugins.jetbrains.com/plugin/25171-hotswaphelper

Hope more people could use with it. 

I will make a pull request if this can be added to the readme.

Thanks.

**Comment by skybber** [comment]
@gejun123456 : Yes, please do it. It will provide users with valuable information how to use the plugin. Btw did you consider plugin package placement to `org.hotswap.plugin` instead of `com.myhotswap` ?

**Comment by gejun123456** [comment]
will replace it later. Thanks for the suggestion

**Comment by homejim** [comment]
Cool

**Comment by skybber** [comment]
done
