### ISSUE TITLE
[spring] Refresh @Autowired field

### ISSUE THREAD

**Issue by gdrouet** [HotswapProjects/HotswapAgent#58]
Hi

when I add a new attribute annotated with Autowired, the value stills null after refresh. The spring plugin is enable because I see outputs when the bean is reloaded.

Did I miss something or this kind of support is not already provided by the agent?

Thanks!

**Comment by vishu018** [comment]
I am facing the same issue.  Any help is appreciated.

**Comment by edudant** [comment]
This should work in current version. Please reopen if still valid.

**Comment by roman-hak** [comment]
Tried versions 1.1 and 1.1.0-SNAPSHOT and still experiencing the same issue :-(
