### ISSUE TITLE
HotswapAgent watch /.m2/repository/   directory

### ISSUE THREAD

**Issue by xiangpingjiang** [HotswapProjects/HotswapAgent#588]
I have ERROR like below:
`HOTSWAP AGENT: 17:17:55.352 WARNING (org.hotswap.agent.watch.nio.WatcherNIO2) - Unable to watch for path file:///workspaces/doraemon-prod/jar:file:/home/vscode/.m2/repository/com/alipay/sofa/common/sofa-common-tools/1.3.11/sofa-common-tools-1.3.11.jar!/sofa-thread/log/log4j2, not a local regular file or directory.`

and I have tried add `exclude=file:/.m2/repository/**` and `exclude=jar:*`  in maven:    src/main/resources/hotswap-agent.properties   
But it did't take effet.

How can I exclude /.m2/repository/ directory? 
Thank you

**Comment by skybber** [comment]
You can ignore this log, will be fiex in next release
