### ISSUE TITLE
[jersey] jvm error when I change method signature

### ISSUE THREAD

**Issue by gdrouet** [HotswapProjects/HotswapAgent#59]
When I change a the following method's parameter in the signature with jersey 1.11:
```java
	@POST
	@Consumes("application/json")
	@Produces("application/json")
	@Path("/colors")
	public List<LightColorView> findAllLigthColorsByType(final RequestCriterias criterias) {
		return this.noeudCoordinator.findAllColorsByType(criterias);
	}
```
 I get the following error:

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000245eb24, pid=692, tid=3664

 JRE version: Java(TM) SE Runtime Environment (7.0_71-b14) (build 1.7.0_71-b14)
 Java VM: Dynamic Code Evolution 64-Bit Server VM (24.71-b01-dcevmlight-2 mixed mode windows-md64 compressed oops)
 Problematic frame:
 j  om.capgemini.configurator.spaceo.core.dto.request.RequestCriterias.setNodeType(Ljava/lang/String)V+0

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 D:\tools\apache-tomcat\7.0.55\bin\hs_err_pid692.log

 If you would like to submit a bug report, please visit:
   http://ssw.jku.at/dcevm/bugreport/

**Comment by edudant** [comment]
Java crash looks more like DCEVM issue, if it is still valid, please use https://github.com/dcevm/dcevm
