### ISSUE TITLE
How to measure the time for each hot reload?

### ISSUE THREAD

**Issue by homejim** [HotswapProjects/HotswapAgent#592]
I want to measure the time taken for each hot reload. For example, when I modify A.java, how much time in total is spent by hotswapagent in processing it?

**Comment by homejim** [comment]
@skybber Do you have any suggestions?

**Comment by skybber** [comment]
You can use `-Xlog:redefine+class*=info ` to see how much time it spends in dcevm, but there are no time measures in  HotswapAgent. It also depends, which HotswapAgent are you using. In many cases plugins triggers secondary redefinition  after primary redefinition after some timeout, depending on plugin, it can be 0.5-2s.

**Comment by homejim** [comment]
> You can use `-Xlog:redefine+class*=info ` to see how much time it spends in dcevm, but there are no time measures in HotswapAgent. It also depends, which HotswapAgent are you using. In many cases plugins triggers secondary redefinition after primary redefinition after some timeout, depending on plugin, it can be 0.5-2s.

thanks
