### ISSUE TITLE
Spring plugin reload unsuccessful: When modifying parameters in RequestParam separately.

### ISSUE THREAD

**Issue by homejim** [HotswapProjects/HotswapAgent#594]
I ran `@RequestParam("id")` int id. Then I changed the parameter to `@RequestParam("id2")`, but it didn't work; it still requires the id parameter instead of id2.

``` 
 @RequestMapping("/hello")
    public ResponseEntity<User> test(@RequestParam("id") int id) {
        User user = userService.load(id);
        return ResponseEntity.ok(user);
    }
```

**Comment by gejun123456** [comment]
https://github.com/gejun123456/HotswapAgent/commit/347c1e87e9468f1c25b27efd693cbfbec3071f7f#diff-15e9a5852d8616f54c9599c79c5fe1597a6824cd17e960eaf52ce7ef1560218cR56
have done some work to make it work, it works for my controller project. It might will help you.

**Comment by homejim** [comment]
> https://github.com/gejun123456/HotswapAgent/commit/347c1e87e9468f1c25b27efd693cbfbec3071f7f#diff-15e9a5852d8616f54c9599c79c5fe1597a6824cd17e960eaf52ce7ef1560218cR56
> have done some work to make it work, it works for my controller project. It might will help you. 
> 
>    
Great!
You can try submitting this code separately as a PR to the master branch.
