### ISSUE TITLE
[jersey1] Refresh annotations

### ISSUE THREAD

**Issue by gdrouet** [HotswapProjects/HotswapAgent#60]
With jersey 1.11, annotations @POST, @GET, @Path are note refreshed.

**Comment by gdrouet** [comment]
PR created. A good start to provide hot reloading for jersey 1.x is here: https://jersey.java.net/documentation/latest/migration.html#d0e17219

Migration guide also compares the two implementations: https://jersey.java.net/documentation/latest/migration.html

**Comment by skybber** [comment]
done.
