### ISSUE TITLE
Hotswap reduces application performance

### ISSUE THREAD

**Issue by UltraBlackLinux** [HotswapProjects/HotswapAgent#610]
Hey there,
I've noticed an issue with hotswap agent that I think I've also had back in the day with DCEVM: With each hotswap my application, minecraft in this case, gets slower and slower up to the point where I have to restart it.
Any idea why that is? Is there a way around this?
Thanks!

**Comment by skybber** [comment]
Please, check if you have version affected by this issue:

https://youtrack.jetbrains.com/issue/JBR-7351/JVM-CodeCache-will-not-be-cleaned-using-G1GC-if-Hotswap-Agent-is-enabled-since-JBR-6419-jbr21.351

it has been fixed in last versions of JBR

**Comment by UltraBlackLinux** [comment]
I'm using `OpenJDK Runtime Environment JBR-21.0.2+13-375.1-jcef (build 21.0.2+13-b375.1)` and yup, on the post that you linked I'm seeing that my version is mentioned as having issues.

I'll update that then, thanks!
