### ISSUE TITLE
HotSwap with DCEVM configured, started but not reloading changes during app execution ( Maven +JFX )

### ISSUE THREAD

**Issue by kinkkong** [HotswapProjects/HotswapAgent#62]
I'm using Netbeans 8 to write sample application based on Maven and Java FX. I want to set up HotSwap with DCEVM and check if it's working with my project.

Sample application
public class FXMLController implements Initializable {

```
@FXML
private Label label;

@FXML
private void handleButtonAction(ActionEvent event) {
    System.out.println("You clicked me!");        
}

@Override
public void initialize(URL url, ResourceBundle rb) {
// TODO
}    
```

}
I've installed and configured DCEVM and HotSwap agent.This is my running configuration:

runfx.args=-Xdebug -Xrunjdwp:transport=dt_socket,server=n,address=${jpda.address} -jar "${project.build.directory}/${project.build.finalName}.jar"
jpda.listen=true
Env.MAVEN_OPTS=-XXaltjvm=dcevm -javaagent:c:\TEST\hotswap-agent.jar=autoHotswap=true
I've also cliked "Compile on save" option in netbeans.

This is log from console during app start.

NetBeans: JPDA Listening Start...
JPDA Address: MC0WKJ3C:50469
Port:50469
cd C:\dev\java\MavenFxHotSwap; "MAVEN_OPTS=-XXaltjvm=dcevm -javaagent:c:\\TEST\\hotswap-agent.jar=autoHotswap=true" JAVA_HOME=C:\TEST\Java\jdk1.8.0_05 cmd /c "\"\"C:\Program Files\NetBeans 8.0.2\java\maven\bin\mvn.bat\" -Drunfx.args=\"-Xdebug -Xrunjdwp:transport=dt_socket,server=n,address=50469 -jar \\"${project.build.directory}/${project.build.finalName}.jar\\" \" -Djpda.listen=true -Djpda.address=50469 -Dmaven.ext.class.path=\"C:\Program Files\NetBeans 8.0.2\java\maven-nblib\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running **NetBeans Compile On Save execution**. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
HOTSWAP AGENT: 11:43:17.728 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.2} - unlimited runtime class redefinition.
HOTSWAP AGENT: 11:43:18.085 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'sun.misc.Launcher$AppClassLoader@58644d46'.
HOTSWAP AGENT: 11:43:18.124 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver, OsgiEquinox]
HOTSWAP AGENT: 11:43:19.472 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'ClassRealm[plexus.core, parent: null]'.
Scanning for projects...

---
## Building MavenFxHotSwap 1.0-SNAPSHOT

HOTSWAP AGENT: 11:43:20.164 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]'.

--- exec-maven-plugin:1.2.1:exec (default-cli) @ MavenFxHotSwap ---
HOTSWAP AGENT: 11:43:21.068 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]'.
HOTSWAP AGENT: 11:43:21.563 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1, parent: sun.misc.Launcher$AppClassLoader@58644d46]'.
When I'm debuging code and making some changes adding method or something no changes are made. I can apply changes via netbeasn interface but no log from HotswapperPlugin is visible. Is there is any way to make it work? Am I doing something wrong?

**Comment by edudant** [comment]
Check http://hotswapagent.org for netbeans setup. You should not mix debugger with hotswapper plugin.

Please reopen if still valid.
