### ISSUE TITLE
NPE when using pluginPackages in hotswap-agent.properties

### ISSUE THREAD

**Issue by martin-macak** [HotswapProjects/HotswapAgent#66]
I tried to create simple plugin inside JAR packaged application. I am getting NPE when application bootstraps with HotSwapAgent attached.
I created simple git repository with the invalid code, which can be found at git@github.com:martin-macak/HotswapAgent-CustomPlugin-Error.git
I also tried this approach on HotSwapAgentExamples:customPlugin. When packaged as JAR and added Main class/method and manifest, I am getting the same NPE error.

**Comment by edudant** [comment]
I have updated HotSwapAgentExamples:customPlugin and it works as a JAR with current HA version. Please try it.
