### ISSUE TITLE
Why code dosen't hot swap when running DCEVM and HotAgent on Tomcat 7?

### ISSUE THREAD

**Issue by kinkkong** [HotswapProjects/HotswapAgent#68]
I'm using Tomcat 7 with DCEVM and HotAgent. Tomcat is starting normally wiht HotSwap log.

    HOTSWAP AGENT: 11:4:10.958 INFO (org.hotswap.agent.HotswapAgent) - Loading        
    Hotswap agent {0.2} - unlimited runtime class redefinition.
    HOTSWAP AGENT: 11:4:11.145 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver, OsgiEquinox]

I'm connecting to Tomcat via remote debuger. Eclipse is using save DCEVM as runtime env. When change is made in eclipse this log appears

    HOTSWAP AGENT: 11:23:53.322 RELOAD (org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin) - Class 'PATH/LoginView' has been enhanced with anonymous classes for hotswap.

No change is made. Running debuger, it is not going through new line which is simple System.out.println("test").

setenv.bat below:
     set JAVA_HOME=C:\Program Files\Java\jdk1.7.0_67
     set JRE_HOME=C:\Program Files\Java\jdk1.7.0_67\jre
     set JAVA_OPTS=-javaagent:hotswap-agent.jar

Java version:

    java version "1.7.0_67"
    Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
    Dynamic Code Evolution 64-Bit Server VM (build 24.71-b01-dcevmlight-2, mixed mode)

**Comment by skybber** [comment]
Try to follow setup from wiki:  https://github.com/HotswapProjects/HotswapAgent/wiki/Eclipse-setup  I have no problems with the same setup you have

**Comment by guisilver** [comment]
I was with the same problem. Hotswap doesn't works with this version of JDK. Change your JDK to jdk7u71 version or higher.

**Comment by kinkkong** [comment]
@guisilver Ok, thanks a lot! Im able to run it with tomcat added to eclipse. Is it the way to run it on standalone tomcat via JPDA?

**Comment by kinkkong** [comment]
It seems hotswap agent is not supporting Vaadin 7, when I changed something related to spring everything worked just fine.
