### ISSUE TITLE
Error occurred during initialization of VM Unable to load native library: The specified procedure could not be found

### ISSUE THREAD

**Issue by krishna81m** [HotswapProjects/HotswapAgent#79]
Following the link here http://hotswapagent.org/quick-start with
https://github.com/dcevm/dcevm/releases/download/light-jdk7u71%2B2/installer-light-jdk7u71.2.jar
Install dcevm as an "Installed altjvm"
c:\Work\tools>java -jar installer-light-jdk7u71.2.jar

Left the JDK to the same JDK C:\Program Files\Java\jdk1.7.0_79 as I only had one.

Unzipped latest Hotswap agent
https://github.com/HotswapProjects/HotswapAgent/releases/download/v0.2/HotswapAgent-0.2.zip

Updated config to
-XXaltjvm=dcevm
-javaagent:C:\Work\tools\HotswapAgent-0.2\hotswap-agent.jar

Error occurred during initialization of VM Unable to load native library: 
The specified procedure could not be found

**Comment by krishna81m** [comment]
My bad, I had minor version 79 whereas this supports 71.

**Comment by skybber** [comment]
It is only in the repository now, not released yet. May be Ivan will do the build since u79 can be the last java7 release.
