### ISSUE TITLE
Fresh clone does not pass tests

### ISSUE THREAD

**Issue by spelletier** [HotswapProjects/HotswapAgent#80]
A fresh clone from the repo, tried mvn install and I got:
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project hotswap-agent-jetty-plugin:

**Comment by skybber** [comment]
Unfortunately I have any problems with tests. Could you, please, send more information :
* log file
* your system configuration
* what version of DCEVM are you using

**Comment by spelletier** [comment]
On Mac 10.10.3, I tried Oracle jdk1.7.0_79 patched using the latest DCEVM installer-light-jdk7u71.2 build 2. I also tried the jdk1.8.0_45 with DCEVM-light-8u45 build 15.

MacBook-Pro-de-Samuel:HotswapAgent sam$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"


The end of the log:  
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[DEBUG] boot classpath:  /Users/sam/.m2/repository/org/apache/maven/surefire/surefire-booter/2.15/surefire-booter-2.15.jar  /Users/sam/.m2/repository/org/apache/maven/surefire/surefire-api/2.15/surefire-api-2.15.jar  /Users/sam/work/HotswapAgent/plugin/hotswap-agent-jetty-plugin/target/test-classes  /Users/sam/work/HotswapAgent/plugin/hotswap-agent-jetty-plugin/target/classes  /Users/sam/work/HotswapAgent/hotswap-agent-core/target/hotswap-agent-core-0.2.1-SNAPSHOT.jar  /Users/sam/.m2/repository/junit/junit/4.11/junit-4.11.jar  /Users/sam/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar  /Users/sam/.m2/repository/org/apache/maven/surefire/surefire-junit4/2.15/surefire-junit4-2.15.jar
[DEBUG] boot(compact) classpath:  surefire-booter-2.15.jar  surefire-api-2.15.jar  test-classes  classes  hotswap-agent-core-0.2.1-SNAPSHOT.jar  junit-4.11.jar  hamcrest-core-1.3.jar  surefire-junit4-2.15.jar
Forking command line: /bin/sh -c cd /Users/sam/work/HotswapAgent/plugin/hotswap-agent-jetty-plugin && /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/bin/java -XXaltjvm=dcevm -javaagent:/Users/sam/work/HotswapAgent/hotswap-agent-core/target/hotswap-agent-core-0.2.1-SNAPSHOT.jar -jar /Users/sam/work/HotswapAgent/plugin/hotswap-agent-jetty-plugin/target/surefire/surefirebooter2051976284990699814.jar /Users/sam/work/HotswapAgent/plugin/hotswap-agent-jetty-plugin/target/surefire/surefire5814524830972928526tmp /Users/sam/work/HotswapAgent/plugin/hotswap-agent-jetty-plugin/target/surefire/surefire_38128004646576755619tmp
HOTSWAP AGENT: 13:17:29.642 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.2.1-SNAPSHOT} - unlimited runtime class redefinition.
Running org.hotswap.agent.plugin.jetty.ExtraPathResourceClassLoaderTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.723 sec <<< FAILURE! - in org.hotswap.agent.plugin.jetty.ExtraPathResourceClassLoaderTest
testGetResource(org.hotswap.agent.plugin.jetty.ExtraPathResourceClassLoaderTest)  Time elapsed: 5.677 sec  <<< FAILURE!
java.lang.AssertionError: Returned after modification
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.hotswap.agent.plugin.jetty.ExtraPathResourceClassLoaderTest.testGetResource(ExtraPathResourceClassLoaderTest.java:54)

**Comment by spelletier** [comment]
I think the problem came from the fact the notification occur before the wait. I tried to log the file path and touch it manually and the test passed.

**Comment by spelletier** [comment]
I created a pull request that fix this one but a new one appeared.

Tests in error: 
  WeldPluginTest.newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean:184 » Runtime

I see this multiple time in the log
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.672 sec <<< FAILURE! - in org.hotswap.agent.plugin.weld.WeldPluginTest
newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 0.03 sec  <<< ERROR!
java.lang.RuntimeException: org.hotswap.agent.javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "NewClass"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.hotswap.agent.javassist.ClassPool.toClass2(ClassPool.java:1082)
	at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:1067)
	at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:1019)
	at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:978)
	at org.hotswap.agent.javassist.CtClass.toClass(CtClass.java:1224)
	at org.hotswap.agent.plugin.hotswapper.HotSwapper.newClass(HotSwapper.java:51)
	at org.hotswap.agent.plugin.weld.WeldPluginTest.newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean(WeldPluginTest.java:184)

**Comment by The-Alchemist** [comment]
@spelletier : I don't think that's just you.  I actually get a failing ``WeldPluginTest.newBeanClassIsManagedBeanReRunTestOnlyAfterMvnClean`` with master, so your fix might very well be valid.

**Comment by skybber** [comment]
Peltier : this should be fixed #81, isn't it?
