### ISSUE TITLE
hotswap-agent with Tomcat and Eclipse Exception - during initialization of VM

### ISSUE THREAD

**Issue by Vijaybvrk** [HotswapProjects/HotswapAgent#89]
Hi , 
I have configured hotswap agent in eclipse(version >3.3) and tomcat(version6.0) referring the below two sites.
http://www.hotswapagent.org/quick-start#
http://tirthalpatel.blogspot.com/2014/06/steps-to-setup-hotswap-agent-in-eclipse.html
 I have followed all the steps as it is but am getting below error during tomcat server start up after I add "-XXaltjvm="dcevm" -javaagent:D:\Softwares\hotswap-agent.jar" in tomcat VM arguments. 

Error occurred during initialization of VM
Unable to load native library: The specified procedure could not be found

Please help me to resolve this error and to use hotswap agent with Tomcat and Eclipse successfully.

**Comment by skybber** [comment]
It looks you have dcevm with incompatible openjdk version. Which version of DCEVM / open-jdk have you?

**Comment by Vijaybvrk** [comment]
Thanks for your reply.
JDK version : jdk1.7.0_45
and I downloaded DCEVM-light-8u45.jar from the following path "http://www.hotswapagent.org/quick-start#"

**Comment by skybber** [comment]
It's clear now, you must have same version of JDK and DCEVM. You have several option how to do that:
* upgrade jdk to jdk1.8.0_45
* downgrade DCEVM to 7u45, but there is now such DCEVM release therefore you have to make  DCEVM 
* Uuse dcevm 7u51 https://github.com/dcevm/dcevm/releases/tag/light-jdk7u51%2B10 and upgrade jdk to jdk1.7.0_51 (anyway you can try your old jdk1.7.0_45 with dcevm7u51, it can work together, but I'm not 100% sure...)
