### ISSUE TITLE
Weld/CDI not working as it shoud on Wildfly 8.2

### ISSUE THREAD

**Issue by awillinger** [HotswapProjects/HotswapAgent#93]
Hello,

I am currently in the process of testing out Hotswap Agent for our project(s).
Apart from a NoClassDefFoundError in the beginning (which was solved by compiling the latest Git version myself), it works as it should for the most part.
The only problem I have is that the Weld/CDI plugin is not working, or at least not from what I have seen.
This means that it does not load newly created beans (without a server restart) and also doesn't properly reload them.
So when trying to use them with a @Inject, I either directly get a NPE or later when accessing them.

Running Wildfly 8.2 with latest revision compiled from Git. DCESVM is running as extra VM.

*Example code*
**Main bean**
```java
import java.io.Serializable;

import javax.ejb.Stateful;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.deltaspike.core.api.scope.WindowScoped;

@Named
@WindowScoped
@Stateful
public class Test implements Serializable
{
	private static final long serialVersionUID = -4369854181626140714L;

	@Inject
	private TestInject myInject;

	public String getText() throws Exception
	{
		return "Text: " + myInject.getOne();
	}
}
```
**Injected bean**

```java
import java.io.Serializable;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class TestInject implements Serializable
{
	private static final long serialVersionUID = 7477918131261162722L;

	public String getOne()
	{
		return "test";
	}
}
```

As mentioned, I get a NPE when adding the injected bean newly and directly "using" it.

**Comment by skybber** [comment]
Thanks for report, I'll check it.

**Comment by skybber** [comment]
It looks the problem is caused by ejb (@Stateful), without that it works. I've not tested Agent with ejb  annotation yet since we don't use it in our projects. I'll try to fix it.

**Comment by skybber** [comment]
I did some tests, could you please check if you see message "(org.hotswap.agent.plugin.weld.WeldPlugin) - CDI/Weld plugin initialized in JBossAS." in the logs?

**Comment by awillinger** [comment]
Nope, none of that sort appearing here.

**Comment by skybber** [comment]
I'm able to reproduce the same bug now. We need support for  weld proxy mechanism definitively. It is still missing in hotswap-agent Weld plugin

**Comment by skybber** [comment]
I've added proxy support into HA, it is available in repository. Just now it is restricted only on bean redefinition, new proxied bean class is not supported and probably fails.
